### PR TITLE
Timestamp seperator '-' windows, ':' rest.

### LINKED ISSUE #3000: admin profile stop: cannot download profiles on Windows
## Expected behavior

Profiles are downloaded.

## Actual behavior

```
λ mc admin profile stop local2
mc: <ERROR> Unable to create a backup of profile.zip: open profile.zip.2019-12-09T17:46:18.020573+01:00: The filename, directory name, or volume label syntax is incorrect.
```
The `:` character cannot be used in file names on Windows.

## Steps to reproduce the behavior

* `mc admin profile start -type=trace local2`
* `mc admin profile stop local2`

## mc version

Latest master

```
λ mc version
Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET
```

## System information

Windows.

### PR DESCRIPTION
**Pull request by BigUstad**
Fixes #3000

### CODE REVIEW

File: cmd/admin-profile-stop.go [hunk 1]
```diff
@@ -118,7 +119,12 @@ func mainAdminProfileStop(ctx *cli.Context) error {
 
 	fi, e := os.Stat(downloadPath)
 	if e == nil && !fi.IsDir() {
-		e = moveFile(downloadPath, downloadPath+"."+time.Now().Format("2006-01-02T15:04:05.999999-07:00"))
+		timeStampSeperator := ":"
+		if runtime.GOOS == "windows" {
+			timeStampSeperator = "-"
+		}
+		dtTmFormat := "2006-01-02T15" + timeStampSeperator + "04" + timeStampSeperator + "05.999999-07" + timeStampSeperator + "00"
```
Comment (harshavardhana) [inline cmd/admin-profile-stop.go]: lets make this a global constant @BigUstad

Comment (harshavardhana) [reply cmd/admin-profile-stop.go]: I actually meant to make the entire time stamp format itself as global and also perhaps use - for both windows and unix. It is annoying to have ":" even on Linux environment.

File: cmd/admin-main.go [hunk 2]
```diff
@@ -46,6 +46,10 @@ var adminCmd = cli.Command{
 	},
 }
 
+const dateValueSeparator string = "-"
+const timeStampSeparator string = "-"
+const dateTimeFormatFilename string = "2006" + dateValueSeparator + "01" + dateValueSeparator + "02" + "T" + "15" + timeStampSeparator + "04" + timeStampSeparator + "05.999999-07" + timeStampSeparator + "00"
+
```
Comment (harshavardhana) [inline cmd/admin-main.go]: This can be written perhaps in one line 

```
const dateTimeFormatFilename  = "2006-01-02T15-04-05.999999-07-00"
```
