### PR TITLE
Use colorjson to indent json properly in cp

### LINKED ISSUE #3017: mc mirror --watch: --quiet flag stopped working in latest release (2019-12-17T23-26-28Z)
## Expected behavior
Specifying the `--quiet` flag for `mc mirror --watch` should disable the progress bar.

## Actual behavior
Progress bar appears whether `--quiet` is specified or not.

## Steps to reproduce the behavior
Call `mc mirror --watch` with `--quiet` flag.

## mc version
```
$ mc version
Version: 2019-12-17T23:26:28Z
Release-tag: RELEASE.2019-12-17T23-26-28Z
Commit-id: d92d2f0d4f1c21236cecf5a305bd6679b9527f66
```

## System information
CentOS Linux release 7.7.1908 (Core)

### LINKED ISSUE #3029: copyMessage JSON output not on a single line
## Expected behavior

One JSON object per line.

## Actual behavior

`copyMessage` object [is printed](https://github.com/minio/mc/blob/RELEASE.2019-12-24T23-41-36Z/cmd/cp-main.go#L203-L209) on multiple lines.

## Steps to reproduce the behavior

```
$ mc --json cp play/test/any_filename . | tee /dev/null
{
 "status": "success",
 "source": "play/test/any_filename",
 "target": "any_filename",
 "size": 1098,
 "totalCount": 0,
 "totalSize": 0
}
{"status":"success","total":0,"transferred":1098,"speed":1239.9256198658913}
```
## mc --version

mc version RELEASE.2019-12-24T23-41-36Z

## System information

`mc` tested on windows/amd64 (Windows 10) and linux/amd64 (archlinux).

### PR DESCRIPTION
**Pull request by harshavardhana**
Additionally also do not initialize progress bar in json
or quiet mode in mirror.

Fixes #3029
Fixes #3017

### CODE REVIEW

File: cmd/difference.go [hunk 1]
```diff
@@ -284,6 +284,24 @@ func difference(sourceClnt, targetClnt Client, sourceURL, targetURL string, isMe
 			err := differenceInternal(sourceClnt, targetClnt, sourceURL, targetURL,
 				isMetadata, isRecursive, returnSimilar, dirOpt, diffCh)
 			if err != nil {
+				var ret bool
+				switch err.ToGoError().(type) {
+				// handle this specifically for filesystem related errors.
+				case BrokenSymlink:
```
Comment (krisis) [inline cmd/difference.go]: the switch cases can be simplified like so,
```go
switch err.ToGoError().(type) {
  case BrokenSymlink, TooManyLevelsSymlink, PathNotFound, PathInsufficientPermission:
     ret = true
}
```
