### PR TITLE
session: Close session only if fields have changed.

### LINKED ISSUE #1700: mc: Session list failed with too many open files for more than 1024 sessions.
```
$ ./mc session list | wc -l
mc: <ERROR> Unable to list sessions. open /home/minio/.mc/session/ykdvtkkw.json: too many open files
0
```

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #1700

### CODE REVIEW

File: session-v7.go [hunk 1]
```diff
@@ -258,7 +258,30 @@ func (s *sessionV7) Close() *probe.Error {
...
+	}
+
+	// Save new if only values and fields have changed.
+	if len(changedFields) > 0 {
+		return qs.Save(sessionFile).Trace(sessionFile)
+	}
+
+	// Return success.
+	return nil
 }
```
Comment (abperiasamy) [inline session-v7.go]: Can you move this into Session.save(), which in turn calls Session.isModified().
