### PR TITLE
isTargetURLDir() returns true for aliased URLs with bucket but empty object names

### LINKED ISSUE #1803: mc: incorrect message when bucket does not exist
```
$ mc cp --debug /etc/passwd dist-harsha/test

mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: 65.19.167.91:42001
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=abcd123/20160819/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160819T194708Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 19 Aug 2016 19:47:08 GMT
Server: Minio/DEVELOPMENT.2016-08-19T19-12-51Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: OYMCT9QBU6Z25XJB

f6
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key></Key><BucketName></BucketName><Resource>/test/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  4.68822ms

mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty
 (3) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [/etc/passwd]
 (2) cp-main.go:207 cmd.doCopy(..) Tags: [http://65.19.167.91:42001/test]
 (1) common-methods.go:85 cmd.putTargetStreamFromAlias(..) Tags: [dist-harsha, http://65.19.167.91:42001/test]
 (0) client-s3.go:616 cmd.(*s3Client).Put(..)
 Commit:DEVELOPMENT. | Release-Tag:DEVELOPMENT.GOGET | Host:minio1 | OS:linux | Arch:amd64 | Lang:go1.6 | Mem:1.5MB/9.6MB | Heap:1.5MB/5.7MB
minio@minio1:~/gopath/src/github.com/minio$ mc cp --debug /etc/passwd dist-harsha/test
```

```
$ mc cp --debug /etc/passwd dist-harsha/test/

mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: 65.19.167.91:42001
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=abcd123/20160819/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160819T194736Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 19 Aug 2016 19:47:36 GMT
Server: Minio/DEVELOPMENT.2016-08-19T19-12-51Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: UQ57KF7P173YIOKI

f6
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key></Key><BucketName></BucketName><Resource>/test/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  4.574241ms

mc: <ERROR> Failed to copy ‘/etc/passwd’. Bucket ‘test’ does not exist.
 (3) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [/etc/passwd]
 (2) cp-main.go:207 cmd.doCopy(..) Tags: [http://65.19.167.91:42001/test/passwd]
 (1) common-methods.go:85 cmd.putTargetStreamFromAlias(..) Tags: [dist-harsha, http://65.19.167.91:42001/test/passwd]
 (0) client-s3.go:608 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:minio1 | OS:linux | Arch:amd64 
```

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #1803

### CODE REVIEW

File: cmd/common-methods.go [hunk 1]
```diff
@@ -29,25 +29,32 @@ import (
...
+	c, err := newClient(targetURL)
+	if err == nil {
+		if targetContent, serr := c.Stat(); serr == nil {
+			return targetContent.Type.IsDir()
 		}
-		if strings.HasSuffix(targetURLParse.Path, string(targetURLParse.Separator)) {
-			return true
+		// The target not found, we continue to guess according to bucket/prefix
+		// values in case of s3client
+		if s3c, ok := c.(*s3Client); ok {
```
Comment (harshavardhana) [inline cmd/common-methods.go]: We shouldn't do these things, we are spilling over the details now. We have to validate this properly along with alias in picture Or make it part of the interface `IsDir()`  

Accessing internal functions like this leads to hard bugs.

File: cmd/common-methods.go [hunk 2]
```diff
@@ -29,25 +29,32 @@ import (
...
+	_, aliasedTargetURL, _ := mustExpandAlias(targetURL)
+	if aliasedTargetURL == targetURL {
 		return false
 	}
-	if !targetContent.Type.IsDir() { // Target is a dir.
+	if targetURLParse.Path == string(targetURLParse.Separator) && targetURLParse.Scheme != "" {
 		return false
 	}
-	return true
+	if strings.HasSuffix(targetURLParse.Path, string(targetURLParse.Separator)) {
```
Comment (harshavardhana) [inline cmd/common-methods.go]: This becomes single 

```
return strings.HasSuffix(targetURLParse.Path, string(targetURLParse.Separator))
```
