### PR TITLE
fs: Allow copying to special files if possible.

### LINKED ISSUE #2145: mc cp <filename> to /dev/null should work properly.
## Expected behaviour
```
cp --debug /etc/issue /dev/null 
```
Should work.

## Actual behaviour

```
cp --debug /etc/issue /dev/null 
mc: <ERROR> Failed to copy `/etc/issue`. Requested file `/dev/null` is not a regular file.
 (4) cp-main.go:324 cmd.doCopySession(..) Tags: [/etc/issue]
 (3) common-methods.go:144 cmd.uploadSourceToTargetURL(..) Tags: [/etc/issue]
 (2) common-methods.go:124 cmd.copySourceToTargetURL(..) Tags: [, /dev/null]
 (1) client-fs.go:435 cmd.(*fsClient).Copy(..) Tags: [/dev/null]
 (0) client-fs.go:1039 cmd.(*fsClient).toClientError(..)
 Release-Tag:DEVELOPMENT.2017-05-03T05-08-30Z | Commit:61e511cc3e4d | Host:prtsc | OS:linux | Arch:amd64 | Lang:go1.7.5 | Mem:1.9MB/3.9MB | Heap:1.9MB/2.6MB
mc: <ERROR> Session safely terminated. To resume session `mc session resume tIBWAtnM`
```

## Steps to reproduce the behaviour

Just pick a file and attempt to copy to '/dev/null' 

## mc version
master branch.

## System information
All platforms.

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #2145

### CODE REVIEW

File: cmd/client-fs.go [hunk 1]
```diff
@@ -193,6 +193,20 @@ func (f *fsClient) Watch(params watchParams) (*watchObject, *probe.Error) {
 	}, nil
 }
 
+func shouldOverrideSuffix(objectPath string) bool {
```
Comment (vadmeste) [inline cmd/client-fs.go]: Can you rename this to isCharDevice() or isStreamFile(), it would be easier understand why we are using this.

File: cmd/client-fs.go [hunk 2]
```diff
@@ -203,29 +217,15 @@ func (f *fsClient) put(reader io.Reader, size int64, metadata map[string][]strin
...
-
-	// Proceed if file does not exist. return for all other errors.
-	if e != nil {
-		if !os.IsNotExist(e) {
-			return 0, probe.NewError(e)
-		}
-	}
-
-	// Write to a temporary file "object.part.mc" before commit.
+	overrideSuffix := shouldOverrideSuffix(objectPath)
```
Comment (vadmeste) [inline cmd/client-fs.go]: Can you name this variable avoidResumeUpload ?

File: cmd/client-fs.go (hunk 1 above)
Comment (harshavardhana) [inline cmd/client-fs.go]: done

File: cmd/client-fs.go (hunk 2 above)
Comment (harshavardhana) [inline cmd/client-fs.go]: done
