### PR TITLE
config: Provide meaningful errors for invalid URL and Alias.

### LINKED ISSUE #2232: mc access OVH Openstack container?
I'm trying to access my Openstack container hosted at OVH in their Public Cloud. OVH runs Openstack Swift with Identify v2. I haven't been successful in even connecting to it with mc.

mc gives the following error:

```
mc: <ERROR> URL https://auth.cloud.ovh.net/v2.0 for host https://auth.cloud.ovh.net/v2.0 is not valid. Could not parse it.
```
The endpoints available to me are:
ovh-endpoints

I haven't been able to figure out the aws_access_key or aws_secret_key either, because mc doesn't parse any of the endpoints I have.

Maybe host URL parsing has a bug?

I have submitted a support ticket with OVH to see if they really support S3 compatible API like this Openstack page suggests they should:

https://docs.openstack.org/kilo/config-reference/content/configuring-openstack-object-storage-with-s3_api.html

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #2232

### CODE REVIEW

File: cmd/config-validate.go [hunk 1]
```diff
@@ -54,24 +53,16 @@ func validateConfigFile(config *configV8) (bool, []string) {
...
-		hostErrors = append(hostErrors, errorMsg.String())
+		hostErrors = append(hostErrors, msg)
 	}
-	url := host.URL
-	validURL := isValidHostURL(url)
-	if !validURL {
+	if !isValidHostURL(host.URL) {
 		validationSuccessful = false
-		msg := fmt.Sprintf("URL %s for host %s is not valid. Could not parse it.\n", url, host.URL)
+		msg := "URL `" + host.URL + "` for minio client should be of the form scheme://host[:port]/ without resource component."
```
Comment (vadmeste) [inline cmd/config-validate.go]: Can't you do something like `errInvalidURL(host.URL).ToGoErr().String()` ?

Comment (harshavardhana) [inline cmd/config-validate.go]: Sure..

**Comment by harshavardhana** [comment]
PR updated check again @vadmeste
