### PR TITLE
'rm -r' honors prefix for object and directory names, matching 'ls -r' output

### LINKED ISSUE #3005: mc rm --recursive --force does not delete everything with a given prefix
## Expected behavior
calling `mc rm --force --recursive cluster/bucket/test` should remove all files in `bucket` on `cluster`
## Actual behavior
Errors out saying the object does not exist
## Steps to reproduce the behavior
`mc mb cluster/bucket`
`echo "test" | mc pipe cluster/bucket/test1`
`echo "test" | mc pipe cluster/bucket/test2`
`echo "test" | mc pipe cluster/bucket/test3`
`mc rm --recursive --force cluster/bucket/test`
Error
## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

## Debug output

```
mc: <DEBUG> GET /bucket/?location= HTTP/1.1
Host: HOSTNAME:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20191209/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191209T193914Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 130
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 09 Dec 2019 19:39:15 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Bucket-Region: REDACTED
X-Amz-Request-Id: 15DECB369BA7CEA5
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  58.402496ms

mc: <DEBUG> GET /bucket/?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=0 HTTP/1.1
Host: REDACTED:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20191209/REDACTED/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191209T193915Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 25559
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 09 Dec 2019 19:39:15 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Bucket-Region: REDACTED
X-Amz-Request-Id: 15DECB369D547717
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  25.071632ms

mc: <DEBUG> HEAD /mimg/0 HTTP/1.1
Host: REDACTED:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20191209/REDACTED/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191209T193915Z

mc: <DEBUG> HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 09 Dec 2019 19:39:15 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Bucket-Region: REDACTED
X-Amz-Request-Id: 15DECB36A0156BB7
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  20.032554ms

mc: <DEBUG> GET /REDACTED/?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=0 HTTP/1.1
Host: REDACTED:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20191209/REDACTED/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191209T193915Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 25559
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 09 Dec 2019 19:39:15 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Bucket-Region: REDACTED
X-Amz-Request-Id: 15DECB36A1A470D5
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  34.798185ms

mc: <DEBUG> HEAD /REDACTED/0 HTTP/1.1
Host: REDACTED:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20191209/REDACTED/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191209T193915Z

mc: <DEBUG> HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 09 Dec 2019 19:39:15 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Bucket-Region: REDACTED
X-Amz-Request-Id: 15DECB36A48005AE
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  16.931184ms

mc: <ERROR> Failed to remove `cluster/bucket/test` recursively. Object does not exist
 (2) rm-main.go:257 cmd.removeRecursive(..) Tags: [cluster/bucket/test]
 (1) client-s3.go:1750 cmd.(*s3Client).listRecursiveInRoutineDirOpt(..) Tags: [mimg]
 (0) client-s3.go:1244 cmd.(*s3Client).getObjectStat(..)


```

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #3005
`mc rm -r --force` command fails to remove all matching files/objects, when multiple objecs are needed to be removed by providing a prefix.

### CODE REVIEW

**Comment by ebozduman** [comment]
Since `mc rm -r` command depends on `mc ls -s, I first looked into the ls problem and fixed the existing `mc ls -r` issue, where the command did not list the content  when an inner level prefix is provided.

### Example
Existing hierarchy
```
$ mc ls -r myminio/bucket00/re/pro/duce/pro/blem/
[2019-12-13 16:26:42 PST]     26B 3000
[2019-12-13 16:26:45 PST]     26B 3001
[2019-12-13 16:26:48 PST]     26B 3002
[2019-12-13 16:26:51 PST]     26B 3003
[2019-12-13 16:26:56 PST]     26B 3100
[2019-12-13 16:27:03 PST]     26B 400
[2019-12-13 16:27:05 PST]     26B 401
[2019-12-13 16:27:06 PST]     26B 402
[2019-12-13 16:27:08 PST]     26B 403
[2019-12-16 14:10:59 PST]     26B aaa
[2019-12-16 14:11:04 PST]     26B abb
[2019-12-16 14:11:16 PST]     26B abc
[2019-12-16 18:25:21 PST]     26B problem1000
[2019-12-16 18:25:25 PST]     26B problem1001
[2019-12-16 18:25:28 PST]     26B problem1002
```
where 
`myminio` is the alias
`bucket00` is the bucket
`re/pro/duce/pro/blem` is the prefix/dir structure.

Listing objects with a prefix for the elements at the very tip of the hierarchy always worked fine.
```
$ mc ls myminio/bucket00/re/pro/duce/pro/blem/4
[2019-12-13 16:27:03 PST]     26B 400
[2019-12-13 16:27:05 PST]     26B 401
[2019-12-13 16:27:06 PST]     26B 402
[2019-12-13 16:27:08 PST]     26B 403
```

However, if the provided prefix is chosen in the inner level of the hierarchy, then nothing was listed.
```
$ mc ls myminio/bucket00/re/pro/duce/pro/bl
$
```

Now, with the existing fix (commit cbfdd4dce305), we see the correct output:
```
$ mc ls -r myminio/bucket00/re/pr
[2019-12-13 16:26:42 PST]     26B pro/duce/pro/blem/3000
[2019-12-13 16:26:45 PST]     26B pro/duce/pro/blem/3001
[2019-12-13 16:26:48 PST]     26B pro/duce/pro/blem/3002
[2019-12-13 16:26:51 PST]     26B pro/duce/pro/blem/3003
[2019-12-13 16:26:56 PST]     26B pro/duce/pro/blem/3100
[2019-12-13 16:27:03 PST]     26B pro/duce/pro/blem/400
[2019-12-13 16:27:05 PST]     26B pro/duce/pro/blem/401
[2019-12-13 16:27:06 PST]     26B pro/duce/pro/blem/402
[2019-12-13 16:27:08 PST]     26B pro/duce/pro/blem/403
[2019-12-16 14:10:59 PST]     26B pro/duce/pro/blem/aaa
[2019-12-16 14:11:04 PST]     26B pro/duce/pro/blem/abb
[2019-12-16 14:11:16 PST]     26B pro/duce/pro/blem/abc
[2019-12-16 18:25:21 PST]     26B pro/duce/pro/blem/problem1000
[2019-12-16 18:25:25 PST]     26B pro/duce/pro/blem/problem1001
[2019-12-16 18:25:28 PST]     26B pro/duce/pro/blem/problem1002
```

**Comment by ebozduman** [comment]
More changes are coming for the remove `mc rm -r` issue.

File: cmd/client-s3.go [hunk 1]
```diff
@@ -1853,7 +1854,8 @@ func (c *s3Client) listRecursiveInRoutineDirOpt(contentCh chan *clientContent, d
 			cContent = &clientContent{
 				URL:  url,
 				Time: bucket.CreationDate,
-				Type: os.ModeDir,
+				Type: os.
```
Comment (kannappanr) [inline cmd/client-s3.go]: This change is not required, looks like a formatting change
