### PR TITLE
Functional tests: add a parameter for the full site cleaning test

### LINKED ISSUE #4876: functional tests not working because of a WORM protected file in play.min.io
## Expected behavior

Run all functional tests without errors with default parameters

## Actual behavior

During a functional tests I get:

```
Running functional tests
Dependency validation complete
Running test_make_bucket()
Running test_make_bucket_error()
Running test_rb()
mc: test_rb: /root/mc/mc --config-dir /tmp/.mc-21807 --quiet --no-color rb --force --dangerous myminio  >>> 
mc: <ERROR> Failed to remove `myminio/12345-flwo-whatever`. Object, 'Čo tebe do toho (Version ID=eca82f19-4353-4970-9fbe-a6ea4a1a0c6c)' is WORM protected and cannot be overwritten.
make: *** [Makefile:46: test] Error 1
```

## Steps to reproduce the behavior

`make test`

If I comment this line in `functional_tests.sh`, everything runs fine:

```
assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd rb --force --dangerous "${SERVER_ALIAS}"
```

I get this error because in the `play.min.io` instance, used by default, someone put a WORM protected file named `Čo tebe do toho` in the `12345-flwo-whatever` bucket. So we can't delete all the content of the site. Maybe this test should be disabled in such default case.

## mc --version

mc version DEVELOPMENT.2024-03-13T23-51-57Z (commit-id=2508db9c560c10be0ed2203eaa585134235b6907)
Runtime: go1.22.1 linux/arm64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information

Multiple linux distributions (amd64 or arm64)

### PR DESCRIPTION
**Pull request by davlgd**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Fix #4876 

The latest `mc rb` test clean all the site data, and on the demo site, there are sometimes WORM objects put by some users and it leads to an failure. This test should only be run on sites on which the user knows he can clean everything without errors

## Motivation and Context

I need to run functional tests without errors on the demo site, even if some user put WORM objects in it. The `COMPLETE_RB_TEST` allow to run the "clean everything" test when the user needs it. The parameter name can be changed if it doesn't comply to any mc development rule.

## How to test this PR?

Launch `make test` with `COMPLETE_RB_TEST` parameter set to false/true

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

File: functional-tests.sh [hunk 1]
```diff
@@ -275,13 +278,15 @@ function test_rb()
...
 
     # Test rb with --force and --dangerous to remove a site content
-    assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd mb "${SERVER_ALIAS}/${bucket1}"
-    assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd mb "${SERVER_ALIAS}/${bucket2}"
-    assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd cp "${FILE_1_MB}" "${SERVER_ALIAS}/${bucket1}/${object_name}"
-    assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd cp "${FILE_1_MB}" "${SERVER_ALIAS}/${bucket2}/${object_name}"
-    assert_failure "$start_time" "${FUNCNAME[0]}" mc_cmd rb --force "${SERVER_ALIAS}/"
-    assert_success "$start_time" "${FUNCNAME[0]}" mc_cmd rb --force --dangerous "${SERVER_ALIAS}"
-
+    if [ "${COMPLETE_RB_TEST}" = "true" ]; then
```
Comment (shtripat) [inline functional-tests.sh:281]: Shouldn't this be `if [ "${COMPLETE_RB_TEST}" == "true" ]; then` ?

File: functional-tests.sh [hunk 2]
```diff
@@ -64,6 +64,9 @@ if [ -z "${SERVER_ENDPOINT+x}" ]; then
     ENABLE_HTTPS=1
 fi
 
+# If you want to run the complete site cleaning test, set this variable to true 
+COMPLETE_RB_TEST=false
```
Comment (harshavardhana) [inline functional-tests.sh:68]:
```suggestion
COMPLETE_RB_TEST=true
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by shtripat — APPROVED** [review]

**Comment by bh4t** [comment]
@harshavardhana PTAL when you get a chance.

**Review by harshavardhana — APPROVED** [review]
