### PR TITLE
replicate add should enable all replication types by default

### LINKED ISSUE #4020: Confusing help docs for defaults in `replicate add`'s `--replicate` option
`mc replicate add` will not enable `existing-objects` feature(as the help docs say with regard to `default: ...`), but `mc replicate add --replicate existing-objects` will.

## Expected behavior
` --replicate value             comma separated list to enable replication of soft deletes, permanent deletes, existing objects and metadata sync (valid options are: "delete-marker,delete,existing-objects,metadata-sync"`

## Actual behavior
` --replicate value             comma separated list to enable replication of soft deletes, permanent deletes, existing objects and metadata sync (default: "delete-marker,delete,existing-objects,metadata-sync"`

`ExistingObjectReplication`'s Status is `Disabled`.
```
 mc replicate export AlphaReplication/src-bucket
{
 "Rules": [
  {
   "ID": "c8opc98b5u56ic6mij10",
   "Status": "Enabled",
   "Priority": 0,
   "DeleteMarkerReplication": {
    "Status": "Disabled"
   },
   "DeleteReplication": {
    "Status": "Disabled"
   },
   "Destination": {
    "Bucket": "arn:minio:replication::7b92ad2c-9d6f-4d84-a005-8049a960b009:dst-bucket"
   },
   "Filter": {
    "And": {},
    "Tag": {}
   },
   "SourceSelectionCriteria": {
    "ReplicaModifications": {
     "Status": "Enabled"
    }
   },
   "ExistingObjectReplication": {
    "Status": "Disabled"
   }
  }
 ],
 "Role": ""
}
```

## Steps to reproduce the behavior

`mc replicate add --help`
## mc --version
mc version RELEASE.2022-03-03T21-12-24Z

## System information
```
$ sw_vers
ProductName: Mac OS X
ProductVersion: 10.15.7
BuildVersion: 19H1615
```

### PR DESCRIPTION
**Pull request by harshavardhana**
fixes #4020

### CODE REVIEW

File: cmd/replicate-add.go [hunk 1]
```diff
@@ -167,21 +167,19 @@ func mainReplicateAdd(cliCtx *cli.Context) error {
...
-			case "delete":
-				deleteReplicationStatus = enableStatus
-			case "metadata-sync", "replica-metadata-sync":
-				replicaSync = enableStatus
-			case "existing-objects":
-				existingReplicationStatus = enableStatus
-			default:
-				fatalIf(probe.NewError(fmt.Errorf("invalid value for --replicate flag %s", cliCtx.String("replicate"))), `--replicate flag takes one or more comma separated string with values "delete", "delete-marker", "metadata-sync", "existing-objects" or "" to disable these settings`)
-			}
+	replSlice := strings.Split(cliCtx.String("replicate"), ",")
```
Comment (vadmeste) [inline cmd/replicate-add.go:170]: This means that --replicate will be always mandatory to pass in the cli, is that expected?

Comment (poornas) [reply cmd/replicate-add.go:170]: if --replicate is not passed, it will use the defaults.

Comment (vadmeste) [reply cmd/replicate-add.go:170]: > if --replicate is not passed, it will use the defaults.

Okay, but the new change breaks this behavior. replSlice slice will be always non empty here and it will fail with a fatal() in the next for loop
