### PR TITLE
admin: Add config get command

### LINKED ISSUE #2034: Implement get config command
## Expected behaviour
Having admin get config command

## Actual behaviour
Not having get config command

## Steps to reproduce the behaviour
Obvious

## mc version
All

## System information
All

### PR DESCRIPTION
**Pull request by vadmeste**
The new command is `mc admin config get alias/` and returns a plain config file 

Fixes #2034

### CODE REVIEW

**Comment by vadmeste** [comment]
Ready for review.

File: cmd/admin-config-get.go [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+
+import (
+	"encoding/json"
+
+	"github.com/minio/cli"
+	"github.com/minio/minio/pkg/probe"
+)
+
+var (
+	adminConfigGetFlags = []cli.Flag{}
```
Comment (harshavardhana) [inline cmd/admin-config-get.go]: We don't need this as placeholder.

File: cmd/admin-config-get.go [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+	Name:   "get",
+	Usage:  "Get config of a Minio server/cluster.",
+	Before: setGlobalsFromContext,
+	Action: mainAdminConfigGet,
+	Flags:  append(adminConfigGetFlags, globalFlags...),
+	CustomHelpTemplate: `NAME:
+   {{.HelpName}} - {{.Usage}}
+
+USAGE:
+   {{.HelpName}} ALIAS/
```
Comment (harshavardhana) [inline cmd/admin-config-get.go]: Space character here..

File: cmd/admin-config.go [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package cmd
+
+import "github.com/minio/cli"
+
+var (
+	adminConfigFlags = []cli.Flag{}
```
Comment (harshavardhana) [inline cmd/admin-config.go]: Same we don't need..

File: cmd/admin-config-get.go [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+
+// String colorized service status message.
+func (u configGetMessage) String() string {
+	return string(u.Config)
+}
+
+// JSON jsonified service status Message message.
+func (u configGetMessage) JSON() string {
+	u.Status = "success"
+	statusJSONBytes, e := json.Marshal(u)
```
Comment (harshavardhana) [inline cmd/admin-config-get.go]: what happens with `mc --json` for this? because the `[]byte` is already JSON.

Comment (vadmeste) [inline cmd/admin-config-get.go]: > what happens with mc --json for this? because the []byte is already JSON.

json.Marshal already transforms []byte to base64

**Comment by vadmeste** [comment]
All done.

File: cmd/admin-config-get.go (hunk 4 above)
Comment (harshavardhana) [inline cmd/admin-config-get.go]: Oh we shouldn't do that @vadmeste

Comment (vadmeste) [inline cmd/admin-config-get.go]: > Oh we shouldn't do that @vadmeste

In all cases, we need to apply a transformation of that []byte because it is already inside a json response. For example, quoting ".

Comment (harshavardhana) [inline cmd/admin-config-get.go]: I think base64 is fine because from an API point of view we can't do anything else. They can easily script this out. So i guess --json printing base64 is fine.

**Comment by vadmeste** [comment]
Can we merge this @harshavardhana ?
