### PR TITLE
mv: Check if destination and source are same

### LINKED ISSUE #3229: mc mv deletes file when renaming with the same name
## Expected behavior
mc should not perform any action if source and destination are equals

## Actual behavior
mc "uploads" (actually using X-Amz-Copy-Source) what it considers a new file then delete the old one.
However, as source and destination are the same, the file gets deleted which can be very harmful.

## Steps to reproduce the behavior

Bucket has a few files:
```
mc ls scfr/gbe
[2020-05-23 15:30:29 CEST]     14B glacier1.txt
[2020-05-23 15:30:01 CEST]     12B test-minio.txt
[2020-05-23 15:30:29 CEST]     87B test2.txt
[2020-05-23 16:17:07 CEST]      0B folder_to_sync/
```

One (or a script) can by mistake try to rename a file with the same name:
```
mc --debug mv scfr/gbe/test-minio.txt scfr/gbe/test-minio.txt
mc: <DEBUG> GET /gbe/?location= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200523T141748Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Sat, 23 May 2020 14:17:48 GMT
X-Amz-Id-2: txb616b5001a73415d89d99-005ec9308c
X-Amz-Request-Id: txb616b5001a73415d89d99-005ec9308c

11c
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'</Message><Region>fr-par</Region><RequestId>txb616b5001a73415d89d99-005ec9308c</RequestId></Error>
0

mc: <DEBUG> Response Time:  205.485433ms

mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:48 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx2472d936bfe14ad685838-005ec9308c
X-Amz-Request-Id: tx2472d936bfe14ad685838-005ec9308c
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  99.218006ms

mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:48 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: txe59be44ba2194b7088de9-005ec9308c
X-Amz-Request-Id: txe59be44ba2194b7088de9-005ec9308c
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  102.521856ms

mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:48 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx7c8b1863379d41d4b4c8c-005ec9308c
X-Amz-Request-Id: tx7c8b1863379d41d4b4c8c-005ec9308c
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  101.085173ms

mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:48 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx8165ada2a7614f6fb1002-005ec9308c
X-Amz-Request-Id: tx8165ada2a7614f6fb1002-005ec9308c
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  100.094597ms

mc: <DEBUG> GET /gbe/?object-lock= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2199
Content-Type: application/xml
Date: Sat, 23 May 2020 14:17:48 GMT
X-Amz-Id-2: tx8f918817f91b4aac80c83-005ec9308c
X-Amz-Request-Id: tx8f918817f91b4aac80c83-005ec9308c

mc: <DEBUG> Response Time:  110.979516ms

mc: <DEBUG> GET /gbe/?object-lock= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141748Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2199
Content-Type: application/xml
Date: Sat, 23 May 2020 14:17:49 GMT
X-Amz-Id-2: txc5a9f15dba0a4c81ab3be-005ec9308c
X-Amz-Request-Id: txc5a9f15dba0a4c81ab3be-005ec9308c

mc: <DEBUG> Response Time:  110.848477ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141749Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:49 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx4e3b399e8cdb4dcfb6054-005ec9308d
X-Amz-Request-Id: tx4e3b399e8cdb4dcfb6054-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  95.468378ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141749Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:49 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx86bbea568ad248d694f14-005ec9308d
X-Amz-Request-Id: tx86bbea568ad248d694f14-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  103.661222ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141749Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:49 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: txf88ad8b0fef04190a2409-005ec9308d
X-Amz-Request-Id: txf88ad8b0fef04190a2409-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  88.966249ms

mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141749Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:49 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: tx056937bd80c24c219c7f1-005ec9308d
X-Amz-Request-Id: tx056937bd80c24c219c7f1-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  65.345126ms

.../test-minio.txt:  0 B / 12 B ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃mc: <DEBUG> HEAD /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200523T141749Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 12
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sat, 23 May 2020 14:17:49 GMT
Etag: "b01854d76aa67f457a146c803f70e88f"
Last-Modified: Sat, 23 May 2020 13:30:01 GMT
X-Amz-Id-2: txde637b4301c04054b7ca6-005ec9308d
X-Amz-Request-Id: txde637b4301c04054b7ca6-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  89.504929ms

.../test-minio.txt:  0 B / 12 B ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃mc: <DEBUG> PUT /gbe/test-minio.txt HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-metadata-directive, Signature=**REDACTED**
Content-Type: text/plain
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Copy-Source: gbe/test-minio.txt
X-Amz-Date: 20200523T141749Z
X-Amz-Metadata-Directive: REPLACE
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 224
Content-Type: application/xml
Date: Sat, 23 May 2020 14:17:49 GMT
Last-Modified: Sat, 23 May 2020 14:17:49 GMT
X-Amz-Id-2: txc65e79eeb2e14d5aab593-005ec9308d
X-Amz-Request-Id: txc65e79eeb2e14d5aab593-005ec9308d
X-Amz-Version-Id: 1590240601562947

mc: <DEBUG> Response Time:  175.351224ms

.../test-minio.txt:  12 B / 12 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 19 B/s 0smc: <DEBUG> POST /gbe/?delete= HTTP/1.1
Host: s3.fr-par.scw.cloud
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Content-Length: 78
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200523/fr-par/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: 84TUVuj+YGleoRDTuc2Ufg==
X-Amz-Content-Sha256: abb7be64cb7a0c551253334a2700b74641147c38db55ece8fd76e6caf502575a
X-Amz-Date: 20200523T141749Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 102
Content-Type: text/html; charset=UTF-8
Date: Sat, 23 May 2020 14:17:49 GMT
X-Amz-Id-2: txd934f42cad5a42d59c8f5-005ec9308d
X-Amz-Request-Id: txd934f42cad5a42d59c8f5-005ec9308d

mc: <DEBUG> Response Time:  140.41479ms

```

As a result, the file got deleted from the repository by mc:
```
mc ls scfr/gbe
[2020-05-23 15:30:29 CEST]     14B glacier1.txt
[2020-05-23 15:30:29 CEST]     87B test2.txt
[2020-05-23 16:17:54 CEST]      0B folder_to_sync/
```

## mc --version
mc version RELEASE.2020-05-16T01-44-37Z

## System information
Linux Mint 18, 64bits
mc binary downloaded from Minio website

### PR DESCRIPTION
**Pull request by kannappanr**
If destination and source are the same, it should error out and not try to move

Fixes #3229

### CODE REVIEW

File: cmd/mv-main.go [hunk 1]
```diff
@@ -285,6 +285,15 @@ func mainMove(ctx *cli.Context) error {
 	// check 'copy' cli arguments.
 	checkCopySyntax(ctx, encKeyDB, true)
 
+	if ctx.NArg() == 2 {
+		args := ctx.Args()
+		srcURL := args.Get(0)
+		dstURL := args.Get(1)
+		if srcURL == dstURL {
+			fatalIf(probe.NewError(errors.New("")), fmt.Sprintf("Source and destination urls cannot be the same: %v.", srcURL))
```
Comment (balamurugana) [inline cmd/mv-main.go:293]: You would need to ignore like current behaviour than throwing an error.
```bash
[bala@localhost mc]$ ./mc mv one d1 d1
one:                       2 B / 2 B ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 1.69 KiB/s 0s
[bala@localhost mc]$ ls d1
one
```

Comment (kannappanr) [reply cmd/mv-main.go:293]: @balamurugana The use case here is to fix is the scenario where both the destination and source are objects and not a folder

```
mc mv play/test/issue play/test/issue
```
If both the source and destination are folders, we are already displaying error

```
 $ mc mv play/test/inner/ play/test/inner -r 
mc: <ERROR> Moving a folder into itself is not allowed. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

Comment (balamurugana) [reply cmd/mv-main.go:293]: With the same argument, why can't we error out for `./mc mv file dir dir`?

Comment (kannappanr) [reply cmd/mv-main.go:293]: probably same thing should have been done in `mv` and `cp` earlier.
