### PR TITLE
Stat in Windows: Compare URLs in windows style path

### LINKED ISSUE #2772: mc.exe rm  can't find the object
When I'm using mc on a Unix system it can delete an object. On a Windows host, it can't find the same object

## Expected behavior
It should delete the object.

### On a Windows host
```
mc.exe rm minio/maroulla/kokos.tar
mc.exe : mc.exe: <ERROR> Failed to remove `minio/maroulla/kokos.tar`. Target `minio/maroulla/kokos.tar` not found.
At line:1 char:1
+ mc.exe rm minio/maroulla/kokos.tar
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>...tar` not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
### On a Unix host
```
mc rm --fake  minio/maroulla/kokos.tar
Removing `minio/maroulla/kokos.tar`.
```

## Steps to reproduce the behavior
Run mc.exe rm in a windows system

## mc version
mc.exe version RELEASE.2019-05-01T23-27-44Z

## System information
Windows 10

### PR DESCRIPTION
**Pull request by kannappanr**
Convert user provided URL into windows style to compare in statURL

Fixes #2772

### CODE REVIEW

File: cmd/stat.go [hunk 1]
```diff
@@ -112,6 +113,14 @@ func parseStat(c *clientContent) statMessage {
 	return content
 }
 
+// Return standardized URL to be used to compare later.
+func getStandardizedURL(targetURL string) string {
+	if runtime.GOOS == "windows" {
+		targetURL = strings.Replace(targetURL, "/", "\\", -1)
```
Comment (harshavardhana) [inline cmd/stat.go]: We should use filepath.ToSlash() as needed here not strings.Replace()

Comment (kannappanr) [reply cmd/stat.go]: Used filepath.FromSlash() instead of Strings.Replace

**Comment by kannappanr** [comment]
ping @poornas @ebozduman
