### PR TITLE
error out when bucket not found with proper exitcode

### LINKED ISSUE #3953: "mc mirror" is giving bad exitcode when failing
## Expected behavior
exitcode!=0 when failing

## Actual behavior
Gives back an error message, but a wrong exitcode
```
$ mc mirror --quiet --overwrite --md5 pack1 espinosa-feb/pack1;exitcode=$?;echo "exitcode=$exitcode"
mc: <ERROR> Unable to list comparison retrying.. The specified bucket does not exist.
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
exitcode=0
```
exitcode should not be zero

## Steps to reproduce the behavior
Try to mirror into a non-existent bucket

## mc --version
mc version RELEASE.2022-01-29T01-03-27Z

## System information
linux

### PR DESCRIPTION
**Pull request by harshavardhana**
fixes #3953

### CODE REVIEW

**Comment by harshavardhana** [comment]
PTAL @vadmeste @krisis

File: cmd/difference.go [hunk 1]
```diff
@@ -335,12 +336,20 @@ func difference(ctx context.Context, sourceClnt, targetClnt Client, isMetadata b
...
-			switch err.ToGoError().(type) {
+			switch v := err.ToGoError().(type) {
 			case PathNotFound, PathInsufficientPermission:
 				diffCh <- diffMessage{
 					Error: err,
 				}
 				return
+			case minio.ErrorResponse:
+				switch v.Code {
+				case "NoSuchBucket", "NoSuchKey":
```
Comment (vadmeste) [inline cmd/difference.go:347]: differenceInternal is doing listing - I don't think we will ever have 'NoSuchKey' here

**Review by vadmeste — COMMENTED** [review]
One comment

**Review by krisis — APPROVED** [review]
