### PR TITLE
fix: error out when the source and destination might be subdirectories of each other

### LINKED ISSUE #5170: mc mv command on same bucket delete file
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Original file disappear when executing a wrong move operation on a file in identical bucket 

## Expected Behavior

- the file file1.txt should be found after this wrong move, or give an error as in linux : mv file1.txt . => answer : 
mv: 'file1.txt' and './file1.txt' identify the same file, or give a solution to recover the file.

## Current Behavior

- A wrong operation ( but not possible in a linux terminal ) delete a file

## Possible Solution

- The reason seems to be that minio is doing a copy and a delete action

## Steps to Reproduce (for bugs)

- echo 'file1' > file1.txt
- mc cp file1.txt minio1/bucket1
- mc ls minio1/bucket1/file1.txt => answer : [[2025-03-23 21:38:09 CET]     6B STANDARD file1.txt
- mc mv minio1/bucket1 minio1/bucket1
- mc ls -r minio1 => answer : none
- trying to revert action 
  -  mc undo minio1/bucket1/file1.txt => answer : mc: <ERROR> Undo command works only with S3 versioned-enabled buckets. 

## Context

- I was trying mc commands, and after a wrong command, i found this issue

## Your Environment

* mc --version :
mc version RELEASE.2025-03-12T17-29-24Z (commit-id=c1d5d4cbb4caf05afef3ea06a91a56bd778336de)
Runtime: go1.24.1 linux/amd64
Copyright (c) 2015-2025 MinIO, Inc.

* Version used (`minio --version`): docker exec minio1 minio --version
minio version RELEASE.2025-02-28T09-55-16Z (commit-id=8c2c92f7afdc8386b000c0cb57ecec2ee1f5bcb0)
Runtime: go1.23.6 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html

* Server setup and configuration: docker container

* minio image used : image: minio/minio:RELEASE.2025-02-28T09-55-16Z@sha256:a929054ae025fa7997857cd0e2a2e3029238e31ad89877326dc032f4c1a14259

*  Operating System and version (`uname -a`): ubuntu 22.04 Linux  5.15.0-134-generic minio/minio#145-Ubuntu SMP Wed Feb 12 20:08:39 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by jiuker**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

fix: error out when the source and destination might be subdirectories of each other
fix #5170 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/mv-main.go [hunk 1]
```diff
@@ -210,9 +211,14 @@ func mainMove(cliCtx *cli.Context) error {
...
 		dstURL := args.Get(1)
-		if srcURL == dstURL {
+		// case: mc mv play/mybucket/path play/mybucket
+		if strings.HasPrefix(srcURL, dstURL) {
 			fatalIf(errDummy().Trace(), fmt.Sprintf("Source and destination urls cannot be the same: %v.", srcURL))
 		}
+		// case: mc mv play/mybucket/path play/mybucket/path/path2
+		if strings.HasPrefix(dstURL, srcURL) {
+			fatalIf(errDummy().Trace(), fmt.Sprintf("Source %s contains destination: %v.", srcURL, dstURL))
+		}
```
Comment (shtripat) [inline cmd/mv-main.go:221]: These two conditions can be merged in one with `||` may be and we can have generic message like `Source and destination cannot be same`

File: cmd/mv-main.go [hunk 2]
```diff
@@ -210,9 +211,14 @@ func mainMove(cliCtx *cli.Context) error {
 		args := cliCtx.Args()
 		srcURL := args.Get(0)
 		dstURL := args.Get(1)
-		if srcURL == dstURL {
+		// case: mc mv play/mybucket/path play/mybucket
+		if strings.HasPrefix(srcURL, dstURL) {
```
Comment (harshavardhana) [inline cmd/mv-main.go:215]: HasPrefix is not enough you have to match it with an exact path matching

**Review by harshavardhana — CHANGES_REQUESTED** [review]
The check that you added fails for situations like 

```
mc mv /tmp/file.tmp /tmp/file
```

**Comment by harshavardhana** [comment]
@jiuker will send a separate PR for that from miniohq/ec

File: cmd/client-url.go [hunk 3]
```diff
@@ -267,3 +267,43 @@ func guessURLContentType(urlStr string) string {
...
+		if (i == minIndex-1) && (dstURLParts[i] == "" || srcURLParts[i] == "" || dstURLParts[i] == "*" || srcURLParts[i] == "*") {
+			continue
+		}
+		if srcURLParts[i] != dstURLParts[i] {
+			isPrefix = false
+			break
+		}
+	}
+	return isPrefix
+}
```
Comment (ramondeklein) [inline cmd/client-url.go:309]: Please write a unit-test to check these scenarios.

**Review by ramondeklein — CHANGES_REQUESTED** [review]

File: cmd/mv-main.go [hunk 4]
```diff
@@ -210,8 +210,9 @@ func mainMove(cliCtx *cli.Context) error {
 		args := cliCtx.Args()
 		srcURL := args.Get(0)
 		dstURL := args.Get(1)
-		if srcURL == dstURL {
-			fatalIf(errDummy().Trace(), fmt.Sprintf("Source and destination urls cannot be the same: %v.", srcURL))
+		if isURLPrefix(srcURL, dstURL) {
+			fatalIf(errDummy().Trace(), fmt.Sprintf("The source %v and destination %v might be subdirectories of each other", srcURL, dstURL))
```
Comment (klauspost) [inline cmd/mv-main.go:214]:
```suggestion
			fatalIf(errDummy().Trace(), fmt.Sprintf("The source %v and destination %v cannot be subdirectories of each other", srcURL, dstURL))
```

**Review by klauspost — APPROVED** [review]
No need for being unclear in the error.

**Review by shtripat — APPROVED** [review]
lgtm

**Review by harshavardhana — APPROVED** [review]
