### PR TITLE
Vendorize "github.com/minio/minio/pkg/mimedb" to use its content-type resolutions

### LINKED ISSUE #2559: mc does not recognize csv in windows correctly
## Expected behavior

Right now, MIME type for a CSV file while using with mc select shows xls. We have to use our own MIME type library to reliably get the correct content type for csv objects across platforms.

## Actual behavior
Using a CSV object from windows does not work correctly with mc select SQL feature since the content type is not showing csv.

## Steps to reproduce the behavior
Upload CSV object from a windows computer and see if s3 select works on Linux mc

## Proposed solution
Update the pkg/mime-db package in our own codebase. Update the MIME DB info in our own package, re-vendorize this and test if the correct type is detected.
## mc version
- (paste output of `mc version`)

### PR DESCRIPTION
**Pull request by Praveenrajmani**
`minio/mimedb` does not take os-shipped mimetypes. So that the content-type resolutions are
standardized across cross plaforms. 

Fixes #2559

### CODE REVIEW

File: cmd/client-url.go [hunk 1]
```diff
@@ -228,7 +228,12 @@ func isURLPrefixExists(urlPrefix string, incomplete bool) bool {
 // on failure just return 'application/octet-stream'.
 func guessURLContentType(urlStr string) string {
 	url := newClientURL(urlStr)
-	contentType := mime.TypeByExtension(filepath.Ext(url.Path))
+	var contentType string
+	if objectExt := filepath.Ext(url.Path); objectExt != "" {
```
Comment (harshavardhana) [inline cmd/client-url.go]: can you create a function similar to mimedb.TypeByExtension? it would be better original package has this function. This can help avoid the large modifications on the `mc` end, making sure that `mimedb` is a drop in replacement for `mime` package.

Comment (Praveenrajmani) [reply cmd/client-url.go]: ok . Will send a PR to minio/minio and then re-vendorize this

**Comment by kannappanr** [comment]
Marked blocked per discussion in this PR.

**Comment by Praveenrajmani** [comment]
vendor updated and the PR is ready for review

File: vendor/github.com/minio/minio/pkg/mimedb/Makefile [hunk 2]
```diff
@@ -0,0 +1,17 @@
+# Generate db.go from db.json downloaded nodejs mime-db project.
+# NOTE: Autogenerated db.go needs to be vet proofed. \
+	Manually edit json -> JSON for all variable names
```
Comment (harshavardhana) [inline vendor/github.com/minio/minio/pkg/mimedb/Makefile]: don't need to vendorize this, ignore this from `git reset HEAD^ vendor/github.com/minio/minio/pkg/mimedb/Makefile` and ammend.

Comment (Praveenrajmani) [reply vendor/github.com/minio/minio/pkg/mimedb/Makefile]: done
