### PR TITLE
validation for namespace removal

### LINKED ISSUE #3776: mc rb --force is enough for site-wide removal of buckets
## Expected behavior

As I understand the code in rb-main.go a site-wide removal (e.g. `mc rb <alias>`) should require both the `--force` and `--dangerous` options.

## Actual behavior

It is possible to simply use `mc rb --force <alias>` to remove all buckets the aliased user has access to.

## Steps to reproduce the behavior

1. Run minio as a local S3 server: `./minio server ./data`
2. Setup a `mc alias` for the local S3 server: `./mc alias set local http://localhost:9000 minioadmin minioadmin`
3. Create some buckets and upload objects, e.g.
    ```bash
    for i in {0..5}; do ./mc mb "local/new$i"; ./mc cp mc "local/new$i"; done
    ```
4. Execute `./mc rb --force local`.

## mc --version
- mc version RELEASE.2021-07-27T06-46-19Z

## System information

- Using an openSUSE-Leap-15.2 WSL2 instance on Windows.

### PR DESCRIPTION
**Pull request by sinhaashish**
## Expected behavior
 rm-main.go a site-wide removal (e.g. `mc rm <alias>`) should require both the `--force` and `--dangerous` options.

## Actual behavior

It is possible to simply use `mc rm --force <alias>` to remove all buckets the aliased user has access to.

## Steps to reproduce the behavior

1. Run minio as a local S3 server: `./minio server ./data`
2. Setup a `mc alias` for the local S3 server: `./mc alias set local http://localhost:9000 minioadmin minioadmin`
3. Create some buckets and upload objects, e.g.
    ```bash
    for i in {0..5}; do ./mc mb "local/new$i"; ./mc cp mc "local/new$i"; done
    ```
4. Execute `./mc rm --force local`.

## System information

- Using an openSUSE-Leap-15.2 WSL2 instance on Windows.
Closes #3776

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

File: cmd/rm-main.go [hunk 1]
```diff
@@ -210,7 +210,7 @@ func checkRmSyntax(ctx context.Context, cliCtx *cli.Context, encKeyDB map[string
 		url = filepath.ToSlash(filepath.Clean(url))
 		// namespace removal applies only for non FS. So filter out if passed url represents a directory
 		dir := isAliasURLDir(ctx, url, encKeyDB, time.Time{})
-		if !dir {
+		if dir {
```
Comment (vadmeste) [inline cmd/rm-main.go:213]: @sinhaashish, we have a function call isNamespaceRemoval(), we can simplify the code here, can you do that ?

**Review by vadmeste — CHANGES_REQUESTED** [review]
One comment

File: cmd/rm-main.go (hunk 1 above)
Comment (vadmeste) [inline cmd/rm-main.go:213]: Can you use isNamespaceRemoval() here ?

File: cmd/rm-main.go [hunk 2]
```diff
@@ -242,6 +242,11 @@ func checkRmSyntax(ctx context.Context, cliCtx *cli.Context, encKeyDB map[string
 		fatalIf(errDummy().Trace(),
 			"This operation results in site-wide removal of objects. If you are really sure, retry this command with ‘--dangerous’ and ‘--force’ flags.")
 	}
+	if isNamespaceRemoval && (!isDangerous || !isForce) {
```
Comment (klauspost) [inline cmd/rm-main.go:245]:
```suggestion
	if isNamespaceRemoval && !(isDangerous && isForce) {
```
This is more readable to me (if is namespace removal and not is dangerous and force)

Comment (klauspost) [reply cmd/rm-main.go:245]: This overlaps with the checks above.  It seems we are just throwing more cases into the mix.

Can't we simplify these?

Comment (sinhaashish) [reply cmd/rm-main.go]: @klauspost @vadmeste  PTAL

File: cmd/rm-main.go (hunk 1 above)
Comment (sinhaashish) [reply cmd/rm-main.go:213]: In the code we check if its a directory ,  then find the path to decide if its a name space removal or not. So `isNamespaceRemoval` cant be used there.

Comment (vadmeste) [reply cmd/rm-main.go:213]: > In the code we check if its a directory , then find the path to decide if its a name space removal or not. So `isNamespaceRemoval` cant be used there.

I didn't understand. What I am saying is it L210->L216 seems to be checking if this is a namespace removal or not. Which is what isNamespaceRemoval() is doing as well. So my suggestion is to remove L210->L216 line and replace it with isNamespaceRemoval()

**Review by klauspost — APPROVED** [review]
LGTM. Can't help you decide the thing you are discussing with Anis.

**Review by vadmeste — APPROVED** [review]
LGTM
