### PR TITLE
fix return EOF failure on lines with trailing empty lines

### LINKED ISSUE #5168: `mc head <file>` Returns EOF failure on lines with trailing empty lines
## Expected behavior

I'd expect the `mc head` command to not return an error.

## Actual behavior

Running `mc head` on a file with a trailing newline character causes the command to return an EOF error.

Image

Here's a screenshot with `--debug`

Image

## Steps to reproduce the behavior

Upload a file to MinIO that ends in a newline character. Run `mc head` on that file.

I think this bug comes from [here](https://github.com/minio/mc/blob/0f061900eea9f2965decbd9167e18c04617f6259/cmd/head-main.go#L145). This bug was reproducible using go's `bufio.Reader`

Example go playground:

https://go.dev/play/p/CmMqSopy6l3

## mc --version
- (paste output of `mc --version`)

```
mc version RELEASE.2025-01-17T23-25-50Z (commit-id=cc8758c88da31b95dde7b0b6997980ebfb8b98c4)
Runtime: go1.23.5 linux/amd64
Copyright (c) 2015-2025 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information

```
sh-5.1# uname -v
#22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
```

### PR DESCRIPTION
**Pull request by dormanze**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix #5168

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

File: cmd/head-main.go [hunk 1]
```diff
@@ -142,9 +142,13 @@ func headOut(r io.Reader, nlines int64) *probe.Error {
...
-		if e != nil {
-			return probe.NewError(e)
+		line, _, err := br.ReadLine()
+		if err != nil {
+			if err == io.EOF {
+				break
+			} else {
+				return probe.NewError(err)
+			}
 		}
```
Comment (harshavardhana) [inline cmd/head-main.go:152]:
```suggestion
		if e != nil && !errors.Is(e, io.EOF) {
		        return prob.NewError(e)
		}
		if errors.Is(e, io.EOF) {
		        break
		}
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
more readable

File: cmd/head-main.go (hunk 1 above)
Comment (dormanze) [reply cmd/head-main.go]: sure

**Review by klauspost — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
