### PR TITLE
cat: Print ^? for unprintable characters 

### LINKED ISSUE #2185: [feature] cat: Binary dump on terminal by default can lead to terminal crash.
## Expected behaviour
Avoid binary file to be written to terminal if the data is in binary format. Borrowing ideas from https://github.com/curl/curl/commit/5385450afd61328e7d24b50eeffc2b1571cd9e2f

## Actual behaviour
`mc cat` on a binary file such as video or images can in-fact crash the terminal, some times leads to data loss. 

## Steps to reproduce the behaviour
`mc cat` a video or a image file on a gnome terminal.

## mc version
All versions

## System information
All Linux terminals.

### PR DESCRIPTION
**Pull request by vadmeste**
In terminals, cat avoids directly printing some binary characters, such
as control characters or non printable characters but prints ^? instead,
that way, cat will avoid corrupting terminals

Fixes #2185

### CODE REVIEW

File: cmd/cat-main.go [hunk 1]
```diff
@@ -105,6 +162,13 @@ func catOut(r io.Reader, size int64) *probe.Error {
 	var n int64
 	var e error
 
+	// In case of a user showing the object content in a terminal,
+	// avoid printing control and other bad characters to avoid
+	// terminal session corruption
+	if terminal.IsTerminal(int(os.Stdout.Fd())) {
```
Comment (balamurugana) [inline cmd/cat-main.go]: IMO we would need to introduce an option and work accordingly exactly like `cat -A` option

We shouldn't display control chars in hex automagically.

Comment (vadmeste) [inline cmd/cat-main.go]: > IMO we would need to introduce an option and work accordingly exactly like cat -A option

Looks like I can make an output similar to cat -A but I am not too much convinced how much would that be useful.

However, I don't think we need to add any new option flag: If the output is a terminal, it means the user wants to visually see that data, so I guess we can make the output prettier. But if the output is not a terminal, like `mc cat myminio/testbucket/object >/tmp/file` then we won't modify the output.

What do you think @balamurugana  ?

Comment (balamurugana) [inline cmd/cat-main.go]: @vadmeste I used `cat -A` several times to view text files to know DOS format and tab character.  I have no experience in binary files with that.  We could intelligently print binary files with hex or other encoding.  If we don't go with `cat -A` behavior, someone can use it like `mc cat ... | cat -A`

I see `less` and `cat -A` show same output.

**Comment by harshavardhana** [comment]
what was finally decided on this? @vadmeste @balamurugana @krisis

**Comment by vadmeste** [comment]
The purpose of this PR is to protect the terminal from random contents coming from `mc cat`, it is a common case that the terminal gets corrupted after running a cat on a binary file, however, @balamurugana thinks that we also need to add a flag to `mc cat` to be able to see \r\n characters, though we can do that using `mc cat | cat -A`

We probably need to vote. :)

**Comment by balamurugana** [comment]
@vadmeste after my comment, we discussed more on slack and came to the conclusion that
* no extra argument is required (mc cat -A is not needed)
* this PR would encode binary content like output of `cat -A` or `less` command

**Comment by vadmeste** [comment]
For the sake of simplification, this PR only prints printable characters and all whitespaces, other not printable will be printed as '^?'. This would avoid terminal corrupted.

Tested using the following commands:
```sh
$ dd if=/dev/urandom of=/tmp/random.data bs=1024 count=1024
$ mc cat /tmp/random.data # no more terminal corruption
```

@balamurugana, @krisis, can you review again ?

**Comment by vadmeste** [comment]
> @vadmeste can you add some unit tests here?

Done

**Comment by krisis** [comment]
@vadmeste I tested this PR with the following steps,
```
dd if=/dev/urandom of=/tmp/non-print bs=10K count=1
mc cp /tmp/non-print s1/test/non-print
mc cat s1/test/non-print
```
The last command returns the following error,
```mc: <ERROR> Unable to read from `s1/test/non-print`. Input reader closed pre-maturely. Expected `10240` bytes, but only received `20188` bytes.```

**Comment by vadmeste** [comment]
@krisis, this is fixed. But I had to change nearly everthing, can you review again?

File: cmd/cat-main.go [hunk 2]
```diff
@@ -61,6 +66,55 @@ EXAMPLES:
...
+
+// Read() returns pretty printed binary characters
+func (s prettyStdout) Write(input []byte) (int, error) {
+	inputLen := len(input)
+
+	// Convert no printable characters to '^?'
+	// and fill into s.buffer
+	for len(input) > 0 {
+		r, size := utf8.DecodeRune(input)
+		if unicode.IsPrint(r) || unicode.IsSpace(r) {
```
Comment (krisis) [inline cmd/cat-main.go]: we could simplify this to `unicode.IsPrint(r)` since `' '` is a printable character.

File: cmd/cat_test.go [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+	testCases := []struct {
+		originText string
+		prettyText string
+	}{
+		{"", ""},
+		{"text", "text"},
+		// Check with new lines
+		{"text\r\n", "text\r\n"},
+		{"\ttext\n", "\ttext\n"},
+		// Print unicode and check it is not alterd
```
Comment (krisis) [inline cmd/cat_test.go]: typo: s/alterd/altered

File: cmd/cat-main.go (hunk 2 above)
Comment (vadmeste) [reply cmd/cat-main.go]: > we could simplify this to unicode.IsPrint(r) since ' ' is a printable character.

yeah, true for space, but we need IsSpace() for other characters like '\n', '\r', '\t'

```
unicode.IsPrint('\n') => false
unicode.IsSpace('\n') => true
```

File: cmd/cat_test.go (hunk 3 above)
Comment (vadmeste) [reply cmd/cat_test.go]: > typo: s/alterd/altered

Done
