### PR TITLE
Customizes service help for Windows/Linux users

### LINKED ISSUE #2776: Service help description wrong for windows users
## Expected behavior
Borrowing from https://github.com/minio/minio/issues/7598 we should make this appropriate behavior just like a server.

## Actual behavior
No platform-specific help

## Steps to reproduce the behavior
Just type `mc cp -h` on Windows

## mc version
master

## System information
All supported systems

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #2776

Existing `mc` help examples were not making any distinction between Linux and Windows OS. All examples were in Linux format. 
This change adjusts only the prompt information (`$ ` vs `C:\> `), since the path separator does not matter, that is Windows and MinIO accepts both Unix/Linux style separator `/` and Windows style separator, `\`.
And there were no Environment Variable definitions to adjust in the `mc` help content.

### CODE REVIEW

File: cmd/admin-group-add.go [hunk 1]
```diff
@@ -45,9 +45,7 @@ FLAGS:
   {{end}}
 EXAMPLES:
   1. Add users 'fivecent' and 'tencent' to the group 'allcents':
-     $ set +o history
-     $ {{.HelpName}} myminio allcents fivecent tencent
-     $ set -o history
+     {{.Prompt}} {{.HelpName}} myminio allcents fivecent tencent
```
Comment (eco-minio) [inline cmd/admin-group-add.go]: Is there any windows equivalent to `set +o history` ?  Is it possible to print help based on the OS?  It would be good to keep set -o for linux users at least although it is not a hard requirement.  It looks like you have something that might accomplish this in cmd/admin-user-add.go?

Comment (harshavardhana) [reply cmd/admin-group-add.go]: Its already doing that in another command in cmd/config-host-add.go - it should just use that here as well.

Comment (ebozduman) [reply cmd/admin-group-add.go]: I didn't do it here, because there is no sensitive information to hide here. I think disable/enable history is added here inadvertantly, hence I simply removed them leaving the only adaptive change as `{{.Prompt}}`.
