### PR TITLE
info: Show info of all cluster servers

### LINKED ISSUE #2147: mc admin info fails with Minio master
## Expected behaviour
mc admin info shows server info

## Actual behaviour
mc admin shows an error:

```
mc: <DEBUG> GET /?info= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=minio/20170504/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170504T183450Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/json
Date: Thu, 04 May 2017 18:34:50 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14BB7AF412368FD4

332
[{"Error":null,"Addr":"localhost:9000","Data":{"storage":{"Total":24895426560,"Free":2282676224,"Backend":{"Type":1,"OnlineDisks":0,"OfflineDisks":0,"ReadQuorum":0,"WriteQuorum":0}},"network":{"transferred":1413,"received":2190},"http":{"totalHEADs":{"count":0,"avgDuration":"0s"},"successHEADs":{"count":0,"avgDuration":"0s"},"totalGETs":{"count":2,"avgDuration":"0s"},"successGETs":{"count":2,"avgDuration":"0s"},"totalPUTs":{"count":0,"avgDuration":"0s"},"successPUTs":{"count":0,"avgDuration":"0s"},"totalPOSTs":{"count":0,"avgDuration":"0s"},"successPOSTs":{"count":0,"avgDuration":"0s"},"totalDELETEs":{"count":0,"avgDuration":"0s"},"successDELETEs":{"count":0,"avgDuration":"0s"}},"server":{"uptime":35055864135,"version":"DEVELOPMENT.GOGET","commitID":"DEVELOPMENT.GOGET","region":"us-east-1","sqsARN":null}}}]
0

mc: <DEBUG> Response Time:  2.400739ms

mc: <ERROR> Cannot get service status. json: cannot unmarshal array into Go value of type madmin.ServerInfo
 (0) admin-info.go:188 cmd.mainAdminInfo(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:xps-u | OS:linux | Arch:amd64 | Lang:go1.7.5 | Mem:3.0MB/7.8MB | Heap:3.0MB/4.8MB
```

## Steps to reproduce the behaviour
1. Start Minio master
2. `mc admin info myminio/`

## mc version
master

## System information
All

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2147

### CODE REVIEW

File: cmd/admin-info.go [hunk 1]
```diff
@@ -187,31 +187,35 @@ func mainAdminInfo(ctx *cli.Context) error {
...
-	storageInfo := backendStatus{
-		Total: serverInfo.StorageInfo.Total,
-		Free:  serverInfo.StorageInfo.Free,
-	}
-	if serverInfo.StorageInfo.Backend.Type == madmin.Erasure {
-		storageInfo.Backend = xlBackend{
-			Type:         erasureType,
-			OnlineDisks:  serverInfo.StorageInfo.Backend.OnlineDisks,
-			OfflineDisks: serverInfo.StorageInfo.Backend.OfflineDisks,
+	for _, serverInfo := range serversInfo {
```
Comment (harshavardhana) [inline cmd/admin-info.go]: what happens to the `.Addr` and `.Err` ?  Each storage info should have a heading.. which indicates the address for which this storageInfo is being printed for.. I am not able to see that being used here.

Comment (vadmeste) [inline cmd/admin-info.go]: screenshot from 2017-05-13 20-37-25

This is an example of output but I didn't update the PR until another PR in minio/minio gets merged.

Comment (harshavardhana) [inline cmd/admin-info.go]: Using a arrow signifies more of a hierarchy but here we need to display something closer to `systemctl` output IMO.

For example. 
```
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-24 14:00:24 PDT; 1 months 19 days ago
  Process: 11841 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 1205 (sshd)
    Tasks: 1
   Memory: 1.3M
      CPU: 2.107s
   CGroup: /system.slice/ssh.service
           └─1205 /usr/sbin/sshd -D
```

We can do something like this which is more nicer and readable.

server-online
server-offline

In-case of distributed it has to be a little different in the error scenario but you get the idea.

Comment (harshavardhana) [inline cmd/admin-info.go]: Here is the diff 

```diff
 
 // String colorized service status message.
 func (u infoMessage) String() (msg string) {
-       defer func() {
-               msg = console.Colorize("Info", msg)
-       }()
        // When service is offline
        if !u.Service {
-               msg = "The server is offline."
+               msg += fmt.Sprintf("%s %s\n", console.Colorize("InfoFail", "●"), u.ServerInfo.Addr)
+               msg += fmt.Sprintf("  Uptime : server is %s\n", console.Colorize("InfoFail", "offline"))
                return
        }
+       msg += fmt.Sprintf("%s %s\n", console.Colorize("Info", "●"), u.ServerInfo.Addr)
+       msg = console.Colorize("Info", msg)
        msg += fmt.Sprintf("  Version : %s\n", u.ServerInfo.Properties.Version)
-       msg += fmt.Sprintf("   Uptime : %s\n", timeDurationToHumanizedDuration(u.ServerInfo.Properties.Uptime))
+       msg += fmt.Sprintf("   Uptime : %s since %s\n", console.Colorize("Info", "online"),
+               humanize.Time(time.Now().UTC().Add(-u.ServerInfo.Properties.Uptime)))
        msg += fmt.Sprintf("   Region : %s\n", u.ServerInfo.Properties.Region)
```

Observe the usage of `humanize.Time()` which is much more human readable.

Comment (vadmeste) [inline cmd/admin-info.go]: I addressed your comments @harshavardhana, but getting ridding of humanized-duration.go was not possible right now because humanize.Time() which adds an annoying space due to a bug. We should fork it and try again in a separate PR probably

Comment (harshavardhana) [inline cmd/admin-info.go]: We can change that behavior and customize it for our needs as well.

File: cmd/admin-info.go [hunk 2]
```diff
@@ -94,23 +95,45 @@ type ServerInfo struct {
...
+		msg += "\n"
 	}()
+
+	dot := "●"
+
 	// When service is offline
 	if !u.Service {
-		msg = "The server is offline."
+		msg += fmt.Sprintf("%s  %s\n", console.Colorize("InfoFail", dot), u.Addr)
+		msg += fmt.Sprintf("  Uptime : Server is %s", console.Colorize("InfoFail", "Offline"))
```
Comment (harshavardhana) [inline cmd/admin-info.go]: if `online` is kept in non capitalized we can keep `Offline` as `offline`

File: cmd/admin-info.go [hunk 3]
```diff
@@ -165,8 +189,8 @@ func mainAdminInfo(ctx *cli.Context) error {
 	client, err := newAdminClient(aliasedURL)
 	fatalIf(err, "Cannot get a configured admin connection.")
 
-	// Fetch the server info of the specified Minio server
-	serverInfo, e := client.ServerInfo()
+	// Fetch info of all servers (cluster or single server)
+	serversInfo, e := client.ServerInfo()
```
Comment (harshavardhana) [inline cmd/admin-info.go]: what happens when `serverOffline` is true, does the Addr field empty is handled as well?

File: cmd/admin-info.go (hunk 2 above)
Comment (vadmeste) [inline cmd/admin-info.go]: > if online is kept in non capitalized we can keep Offline as offline

Done

File: cmd/admin-info.go (hunk 3 above)
Comment (vadmeste) [inline cmd/admin-info.go]: > what happens when serverOffline is true, does the Addr field empty is handled as well?

Yeah, you are right. Currently, it shows the alias, and not the address.

**Comment by krisis** [comment]
Tested PR locally, following is the output when one node is down.
```
➜  mc git:(pr2149) mc admin info dminio1
●  localhost:9001
   Uptime : online since 1 minute ago
  Version : 2017-05-20T05:19:52Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 58KiB, Outgoing 128KiB
  Storage : Total 340GiB, Free 136GiB, Online Disks: 3, Offline Disks: 1

●  localhost:9002
   Uptime : online since 1 minute ago
  Version : 2017-05-20T05:19:52Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 50KiB, Outgoing 25KiB
  Storage : Total 340GiB, Free 136GiB, Online Disks: 3, Offline Disks: 1

●  localhost:9003
   Uptime : online since 1 minute ago
  Version : 2017-05-20T05:19:52Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 51KiB, Outgoing 25KiB
  Storage : Total 340GiB, Free 136GiB, Online Disks: 3, Offline Disks: 1

●  localhost:9004
    ERROR : dial-http localhost:9004/minio/admin: dial tcp 127.0.0.1:9004: getsockopt: connection refused

```

**Comment by harshavardhana** [comment]
what does it mean @krisis do you approve or no?

**Comment by krisis** [comment]
@harshavardhana I haven't reviewed the code so I don't approve this PR in that sense. I did test this locally to verify https://github.com/minio/minio/pull/4346 (corresponding changes in `pkg/madmin`), so I shared my results here hoping it may help the reviewers confidence.

**Comment by harshavardhana** [comment]
> @harshavardhana I haven't reviewed the code so I don't approve this PR in that sense. I did test this locally to verify minio/minio#4346 (corresponding changes in pkg/madmin), so I shared my results here hoping it may help the reviewers confidence.

@krisis that part i already did :-) when i did :+1:

**Comment by harshavardhana** [comment]
> ●  localhost:9004
>     ERROR : dial-http localhost:9004/minio/admin: dial tcp 127.0.0.1:9004: getsockopt: connection refused

It would make sense to show `Uptime: offline` and then show the Error in a separate line @vadmeste ?

**Comment by vadmeste** [comment]
yes. I just did this:

```
●  minio1:9000
  Uptime : Server is offline.
   Error : dial-http minio1:9000/minio/admin: dial tcp: lookup minio1 on 127.0.0.11:53: no such host.
```

what do you think?
