### PR TITLE
mc rm  to support  entire namespace removal

### LINKED ISSUE #2250: mc rm --recursive --force option should work on sitename
## Expected behaviour
`mc rm --recursive --force --older-than=90 play 
` should succeed and recursively delete buckets older than 90 days
## Actual behaviour
```
➜  mc git:(master) mc rm --recursive --force  --older-than=90  play
mc: <ERROR> Failed to remove `play` recursively. Bucket `` does not exist.
➜  mc git:(master)
```
## mc version
- (paste output of `mc version`)
Version: 2017-09-06T16:33:47Z
Release-tag: DEVELOPMENT.2017-09-06T16-33-47Z
Commit-id: b3955cc7e8dad50f5f13d072ec71a9e7dd52d38f
## System information
ubuntu 17.04

### PR DESCRIPTION
**Pull request by poornas**
Fixes #2250 
Currently, mc rm --recursive --force works on buckets but not on the entire site. This PR adds support for rm --recursive to delete entire site.

To distinguish full site removal from removing a bucket and provide appropriate warning to the user, the user needs to supply --dangerous flag in addition to the --recursive and --force flags for full site rm.

The rm --recursive --force option will continue to work as before at the bucket level or on the file system.

### CODE REVIEW

File: cmd/rm-main.go [hunk 1]
```diff
@@ -82,16 +87,22 @@ EXAMPLES:
...
 
    4. Remove all objects read from STDIN.
       $ {{.HelpName}} --force --stdin
 
-   5. Drop all incomplete uploads on 'jazz-songs' bucket.
+	 5. Remove all buckets and objects recursively from entire namespace
+      $ {{.HelpName}} --recursive --namespace s3
+
+   6. Remove all buckets and objects older than '90' days from entire namespace
+			$ {{.HelpName}} --recursive --namespace --older-than=90 s3
```
Comment (harshavardhana) [inline cmd/rm-main.go]: Tabbing is off.

File: cmd/rm-main.go [hunk 2]
```diff
@@ -121,14 +132,24 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isNamespace := ctx.Bool("namespace")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		if isHostName(url) {
```
Comment (balamurugana) [inline cmd/rm-main.go]: This method does not work for removing a directory with non-aliases.  For example `mc rm mylocaldir` would fail.  Basically we need to differentiate alias and local dir

File: cmd/rm-main.go [hunk 3]
```diff
@@ -121,14 +132,24 @@ func checkRmSyntax(ctx *cli.Context) {
...
+		}
+	}
 	if !ctx.Args().Present() && !isStdin {
 		exitCode := 1
 		cli.ShowCommandHelpAndExit(ctx, "rm", exitCode)
 	}
-
+	if (isRecursive || isStdin) && isNamespaceRemoval && !isNamespace {
+		fatalIf(errDummy().Trace(),
+			"Full namespace removal requires --namespace option. This operation removes all the buckets on your namespace. Please review carefully before performing this *DANGEROUS* operation.")
```
Comment (balamurugana) [inline cmd/rm-main.go]: This check is not interesting.  removing local file system, we don't need any restriction like that.

File: cmd/rm-main.go [hunk 4]
```diff
@@ -220,27 +241,35 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
...
 
 		urlString := content.URL.Path
-		printMsg(rmMessage{
-			Key:  targetAlias + urlString,
-			Size: content.Size,
-		})
+		// print the rmMessage only if content is a bucket or object. clnt.List lists
+		// prefixes as well which unifies the S3 listing with folder listing - however
+		// these prefixes are not actual objects on s3 and the content.Time defaults to
+		// zero. Filter these out to prevent erroneous rmMessage being printed to console.
```
Comment (balamurugana) [inline cmd/rm-main.go]: You can skip entries those are ending with `/` and having zero time for completeness.

File: cmd/rm-main.go [hunk 5]
```diff
@@ -220,27 +241,35 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
...
 			for !sent {
 				select {
 				case contentCh <- content:
 					sent = true
-				case pErr := <-errorCh:
+				case pErr, ok := <-errorCh:
+					if !ok {
+						close(contentCh)
+						return exitStatus(globalErrorExitStatus)
+					}
```
Comment (balamurugana) [inline cmd/rm-main.go]: We would need to exit on first error here.  This check leads to continuation.  Below is the right logic
```go
case pErr, ok := <-errorCh:
	if ok {
		errorIf(pErr.Trace(urlString), "Failed to remove `"+urlString+"`.")
		switch pErr.ToGoError().(type) {
		case PathInsufficientPermission:
			// Ignore Permission error.
			continue
		}
	}
	close(contentCh)
	return exitStatus(globalErrorExitStatus)
```

IMO, having `ok` is not required because `pErr` will be `nil` on closed channel and we exit anyway.

File: cmd/rm-main.go [hunk 6]
```diff
@@ -264,6 +293,43 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
...
+func isHostName(url string) bool {
+	parts := strings.Split(url, "/")
+	return len(parts) == 1
+}
+
+// removes all the buckets recursively.
+func removeSiteRecursive(url string, isIncomplete bool, isFake bool, older int) (err error) {
+	clnt, pErr := newClient(url)
+	if pErr != nil {
+		errorIf(pErr.Trace(url), "Failed to remove `"+url+"` recursively.")
```
Comment (balamurugana) [inline cmd/rm-main.go]: This is not appropriate error message here.

File: cmd/rm-main.go [hunk 7]
```diff
@@ -285,7 +351,13 @@ func mainRm(ctx *cli.Context) error {
 	// Support multiple targets.
 	for _, url := range ctx.Args() {
 		if isRecursive {
-			err = removeRecursive(url, isIncomplete, isFake, older)
+			if isHostName(url) {
+				if isNamespace {
+					err = removeSiteRecursive(url, isIncomplete, isFake, older)
```
Comment (balamurugana) [inline cmd/rm-main.go]: Unable to understand the need of this function.

Current code fails for below commands
```bash
$ mc rm --recursive --fake --force play
mc: <ERROR> Failed to remove `play` recursively. Bucket `` does not exist.
```

What I am able to visualize with `--namespace` flag is by running `mc rm --recursive --fake --force play`, it could get list of buckets from `play` alias and keep calling `removeRecursive()` with each bucket URL.

File: cmd/rm-main.go [hunk 8]
```diff
@@ -264,6 +293,43 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
 	return nil
 }
 
+func isHostName(url string) bool {
```
Comment (harshavardhana) [inline cmd/rm-main.go]: Add unit tests?

File: cmd/rm-main.go (hunk 4 above)
Comment (poornas) [reply cmd/rm-main.go]: done.

File: cmd/rm-main.go (hunk 2 above)
Comment (poornas) [reply cmd/rm-main.go]: changed this to incorporate feedback

File: cmd/rm-main.go (hunk 8 above)
Comment (poornas) [reply cmd/rm-main.go]: removed this function.

File: cmd/rm-main.go (hunk 6 above)
Comment (poornas) [reply cmd/rm-main.go]: why?

Comment (balamurugana) [reply cmd/rm-main.go]: This is fine because of `pErr.Trace(url)`.  Sorry for the confusion.

File: cmd/rm-main.go [hunk 9]
```diff
@@ -245,7 +246,7 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
 		// prefixes as well which unifies the S3 listing with folder listing - however
 		// these prefixes are not actual objects on s3 and the content.Time defaults to
 		// zero. Filter these out to prevent erroneous rmMessage being printed to console.
-		if !content.Time.IsZero() {
+		if !(content.Time.IsZero() && strings.HasSuffix(urlString, string(filepath.Separator))) {
```
Comment (balamurugana) [inline cmd/rm-main.go]: S3 service sends `/` as separator whereas on windows `\`. We would need to check whether this works on windows or not.

File: cmd/rm-main.go [hunk 10]
```diff
@@ -351,7 +344,7 @@ func mainRm(ctx *cli.Context) error {
 	// Support multiple targets.
 	for _, url := range ctx.Args() {
 		if isRecursive {
-			if isHostName(url) {
+			if !isAliasURLDir(url) && (strings.Count(url, string(filepath.Separator)) == 0) {
```
Comment (balamurugana) [inline cmd/rm-main.go]: same as above

Comment (poornas) [reply cmd/rm-main.go]: isAliasURLDir is used internally by the checkCopySyntax function. Here the intent is to make sure only the alias is entered, and it is at the root level not a subdirectory.

**Comment by poornas** [comment]
@harshavardhana and @balamurugana , updated the PR with a different approach - recursive removal is handled agnostic to fs/s3.

**Comment by harshavardhana** [comment]
> To distinguish full site removal from removing a bucket and provide appropriate warning to the user, the user needs to supply --dangerous flag in addition to the --recursive and --force flags for full site rm.

Tested the PR `mc rm -r --force play/`  seems to delete everything, but strangely `--dangerous` flag is removed was that intended?

**Comment by poornas** [comment]
that was an intermediate commit - updated the PR to fix messaging  as well.

**Comment by harshavardhana** [comment]
Can you sqaush the commits here,. Will test once again after they are squashed.

**Comment by poornas** [comment]
done.

File: cmd/rm-main.go [hunk 11]
```diff
@@ -82,16 +88,22 @@ EXAMPLES:
    1. Remove a file.
       $ {{.HelpName}} 1999/old-backup.tgz
 
-   2. Remove all objects recursively.
+   2. Remove all objects recursively from a bucket.
```
Comment (harshavardhana) [inline cmd/rm-main.go]: `Remove all objects recursively from bucket 'jazz-songs' matching 'louis' prefix.`

File: cmd/rm-main.go [hunk 12]
```diff
@@ -82,16 +88,22 @@ EXAMPLES:
...
       $ {{.HelpName}} --recursive s3/jazz-songs/louis/
 
-   3. Remove all objects older than '90' days.
+   3. Remove all objects older than '90' days from a bucket.
```
Comment (harshavardhana) [inline cmd/rm-main.go]: Same as above but with 'older than 90 days'

File: cmd/rm-main.go [hunk 13]
```diff
@@ -82,16 +88,22 @@ EXAMPLES:
...
       $ {{.HelpName}} --recursive --older-than=90 s3/jazz-songs/louis/
 
    4. Remove all objects read from STDIN.
       $ {{.HelpName}} --force --stdin
 
-   5. Drop all incomplete uploads on 'jazz-songs' bucket.
+   5. Remove all buckets and objects recursively from host
```
Comment (harshavardhana) [inline cmd/rm-main.go]: `Remove all buckets and objects recursively from S3 host`

**Comment by poornas** [comment]
@harshavardhana  and @balamurugana , review comments were addressed. needs a revisit.

File: cmd/rm-main.go [hunk 14]
```diff
@@ -121,17 +133,32 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		if !isAliasURLDir(url) && (strings.Count(url, string(filepath.Separator)) == 0) {
```
Comment (balamurugana) [inline cmd/rm-main.go]: 1. Please add a comment about meaning of this logic.
2. `()` around `strings.` is not required.

File: cmd/rm-main.go [hunk 15]
```diff
@@ -219,12 +247,12 @@ func removeRecursive(url string, isIncomplete bool, isFake bool, older int) erro
 			}
 		}
 
-		urlString := content.URL.Path
-		printMsg(rmMessage{
-			Key:  targetAlias + urlString,
-			Size: content.Size,
-		})
-
+		if !(content.Time.IsZero() && strings.HasSuffix(urlString, string(filepath.Separator))) {
```
Comment (balamurugana) [inline cmd/rm-main.go]: Please add a comment about this check

File: cmd/rm-main.go (hunk 14 above)
Comment (poornas) [reply cmd/rm-main.go]: done

File: cmd/rm-main.go (hunk 15 above)
Comment (poornas) [reply cmd/rm-main.go]: done.

File: cmd/rm-main.go [hunk 16]
```diff
@@ -121,17 +133,34 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		// check if url represents just the namespace without bucket or object prefix specified
+		// in the url
+		if !isAliasURLDir(url) && strings.Count(url, string(filepath.Separator)) == 0 {
```
Comment (balamurugana) [inline cmd/rm-main.go]: A valid input `s3/` and unusual input `s3//` wouldn't work here.  We need to take care properly i.e. we shouldn't use `strings.Count()` inside use url to alias conversion.

If mentioned input is not supported, we have to error out properly.

Comment (poornas) [reply cmd/rm-main.go]: you are correct @balamurugana , added additional validation so that user input errors are caught right away.

File: cmd/rm-main.go [hunk 17]
```diff
@@ -121,17 +133,54 @@ func checkRmSyntax(ctx *cli.Context) {
...
+			fatalIf(err.Trace(aliasedURL), "Failed to remove `"+aliasedURL+"`.")
+		}
+		// validate extraneus delimiters such as play// which won't be caught by previous check
+		if path != "" && bucket == "" {
+			fatalIf(err.Trace(aliasedURL), "Failed to remove `"+aliasedURL+"`.")
 
+		}
+		if alias != "" && path == "" && isBucketEmpty {
+			isNamespaceRemoval = true
+			break
```
Comment (balamurugana) [inline cmd/rm-main.go]: The whole checker logic is confusing to me.  In `rm`  we should not check for bucket or object which is completely abstracted by client interface.  I see below logic is good enough

```go
url = filepath.ToSlash(url)
if !isAliasURLDir(url) {
    alias, path := url2Alias(url)
    isNamespaceRemoval = (path == "")
}
```

Comment (poornas) [reply cmd/rm-main.go]: without the check on lines 157-158, errors like mc rm play// wont be caught. Earlier it was being caught in s3 api because bucket name was not permitted to be empty. Now by allowing namespace removal, bucket name can be empty and there is no way to validate cases like multiple consecutive / delimiters being entered as input. Lines 160-163 can be replaced by the logic you proposed.

Comment (balamurugana) [reply cmd/rm-main.go]: I see `url = filepath.ToSlash(url)` is wrong, you should use `url = filepath.Clean(url)`

Comment (poornas) [reply cmd/rm-main.go]: done.

File: cmd/rm-main.go [hunk 18]
```diff
@@ -121,17 +133,34 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		url = filepath.Clean(url)
```
Comment (balamurugana) [inline cmd/rm-main.go]: you could use `path.Clean()` to work with MS Windows.

Comment (poornas) [reply cmd/rm-main.go]: doesn't filepath.Clean do the same?

Comment (balamurugana) [reply cmd/rm-main.go]: no

Comment (harshavardhana) [reply cmd/rm-main.go]: path.Clean() doesn't do anything on windows @balamurugana @poornas - filepath.Clean() should be used for cross platform friendly behavior.

Comment (balamurugana) [reply cmd/rm-main.go]: See below.  This had been discussed long back

```go
package main

import (
	"fmt"
	"path"
	"path/filepath"
)

func main() {
	fmt.Println("filepath.Clean():")
	fmt.Println(filepath.Clean("/s3"))
	fmt.Println(filepath.Clean("s3/"))
	fmt.Println(filepath.Clean("s3/mybucket//object//"))
	fmt.Println(filepath.Clean(`\s3`))
	fmt.Println(filepath.Clean(`s3\`))
	fmt.Println(filepath.Clean(`s3\mybucket\\object\\`))

	fmt.Println("path.Clean():")
	fmt.Println(path.Clean("/s3"))
	fmt.Println(path.Clean("s3/"))
	fmt.Println(path.Clean("s3/mybucket//object//"))
	fmt.Println(path.Clean(`\s3`))
	fmt.Println(path.Clean(`s3\`))
	fmt.Println(path.Clean(`s3\mybucket\\object\\`))
}
```

On MS Windows
```
filepath.Clean():
\s3
s3
s3\mybucket\object
\s3
s3
s3\mybucket\object
path.Clean():
/s3
s3
s3/mybucket/object
\s3
s3\
s3\mybucket\\object\\
```

On GNU/Linux

```
filepath.Clean():
/s3
s3
s3/mybucket/object
\s3
s3\
s3\mybucket\\object\\
path.Clean():
/s3
s3
s3/mybucket/object
\s3
s3\
s3\mybucket\\object\\
```

Comment (harshavardhana) [reply cmd/rm-main.go]: i don't think so you understand the problem of using path.Clean() , path.Clean() doesn't work on windows since it never cleans paths such as `\\` or `C:\mypath\...\otherdir\` . path.Clean() doesn't understand C:\ etc. so it would be wrong to use path.Clean() for cross platform reasons. 

For `mc` we do support such paths and need to behave properly for windows natively once we do filepath.Clean() if we want all the `\` to `/` then we should use filepath.ToSlash() to convert the paths properly.

Using code like in this manner `filepath.ToSlash(filepath.Clean(p))` would work for all operating systems.

Comment (balamurugana) [reply cmd/rm-main.go]: How is it possible to store object name containing `\`?

Comment (harshavardhana) [reply cmd/rm-main.go]: filepath.ToSlash is used to do proper Windows translation, filepath.ToSlash has no effect on Unixes. Now if you are arguing that if there are files which have `\` on Linux then they are stored fine with this mechanism as well.  Now on windows there is no filename which explicitly contains `\` since its a separator. 

Here is how the behavior is 

- filepath.ToSlash converts all `\` on Windows to `/` 
- filepath.ToSlash converts all `/` to '/` on Unixes. 

filepath.ToSlash is not ubiquitously converting `\` to `/` - https://play.golang.org/p/fFPdEZoAEf

**Comment by harshavardhana** [comment]
@poornas can you squash your changes? would it possible to bring in some unit tests as well if possible?

File: cmd/rm-main.go [hunk 19]
```diff
@@ -121,17 +134,34 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		url = path.Clean(url)
```
Comment (harshavardhana) [inline cmd/rm-main.go]: It is required to perhaps bring change like this instead `filepath.ToSlash(filepath.Clean(url))` here, for windows paths such as `C:\` path.Clean will not work.

Also question for me why is this path.Clean needed? is it for isAliasURLDir() ? A comment would be needed i think here.

Comment (poornas) [reply cmd/rm-main.go]: @y4m4,  on further thinking, the path.Clean and isAliasURLDir() check are superfluous and can be dispensed with altogether.

Comment (harshavardhana) [reply cmd/rm-main.go]: Okay that would be better.

**Comment by poornas** [comment]
@harshavardhana , have not introduced stand alone functions that can be unit tested here. It might be worthwhile to add a mint cleanup function in the functional tests that exercises this code - but that will cleanup play server and may not be entirely good.

**Comment by harshavardhana** [comment]
> @harshavardhana , have not introduced stand alone functions that can be unit tested here. It might be worthwhile to add a mint cleanup function in the functional tests that exercises this code - but that will cleanup play server and may not be entirely good.

Okay that makes sense.

File: cmd/rm-main.go [hunk 20]
```diff
@@ -121,17 +133,31 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		_, path := url2Alias(url)
```
Comment (balamurugana) [inline cmd/rm-main.go]: What are all expected behaviors for below command line arguments?
```
1. mc rm mylocaldir
2. mc rm mylocaldir/
3. mc rm mylocalfile
4. mc rm c:
5. mc rm c:\
```

Comment (poornas) [reply cmd/rm-main.go]: ➜  mc git:(rr2) mkdir mylocaldir
➜  mc git:(rr2) mc rm mylocaldir 
Removing `mylocaldir`.
➜  mc git:(rr2) mkdir mylocaldir
➜  mc git:(rr2) touch mylocaldir/testfile
➜  mc git:(rr2) ✗ mc rm mylocaldir 
Removing `mylocaldir`.
mc: <ERROR> Failed to remove `mylocaldir`. remove mylocaldir: directory not empty
➜  mc git:(rr2) ✗ mc rm mylocaldir 
Removing `mylocaldir`.
mc: <ERROR> Failed to remove `mylocaldir`. remove mylocaldir: directory not empty

Comment (poornas) [reply cmd/rm-main.go]: however, removing the isAliasURLDir() check will interfere with mc rm messaging in recursive removal. Which is why the check was introduced in the first place - for filtering out fs.
```➜  mc git:(rr2) ✗ mc rm --r --force mylocaldir 
mc: <ERROR> Full site removal requires --dangerous option. This operation removes all the buckets on your namespace. Please review carefully before performing this *DESTRUCTIVE* operation. ```

Comment (poornas) [reply cmd/rm-main.go]: @harshavardhana and @balamurugana , added the isAliasURLDir() check back and a comment on why it is needed.

File: cmd/rm-main.go [hunk 21]
```diff
@@ -121,17 +133,34 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		// namespace removal applies only for non FS. So filter out if passed url represents a directory
+		if !isAliasURLDir(url) {
+			_, path := url2Alias(url)
```
Comment (balamurugana) [inline cmd/rm-main.go]: Does `url2Alias()` take care of returning clean path including windows UNC path?

Comment (poornas) [reply cmd/rm-main.go]: yes, see test output below..
```
C:\go\bin> cd ..\src\github.com\minio\mc
C:\go\src\github.com\minio\mc [rr2 ≡]> mc rm --r --force \\myserver\myfolder\myfile
mc.exe: <ERROR> Failed to remove `\\myserver\myfolder\myfile` recursively. open \\myserver\myfolder\myfile: The network name cannot be found.
C:\go\src\github.com\minio\mc [rr2 ≡]> mc rm --r --force C:
Removing `C:.git\FETCH_HEAD`.

C:\go\src\github.com\minio\mc> mc rm C:\
Removing `C:\`.
mc.exe: <ERROR> Failed to remove `C:\`. Insufficient permissions to access this file `C:\`
C:\go\src\github.com\minio\mc>
C:\go\src\github.com\minio\mc> mc rm C:
Removing `C:`.
mc.exe: <ERROR> Failed to remove `C:`. remove C:: The process cannot access the file because it is being used by a
ther process.
C:\go\src\github.com\minio\mc>

C:\go\src\github.com\minio\mc> mc rm --r --force  C:
Removing `C:cmd\mc_test.go`.

~> mc mb a/b/c/d
~> mc rm a
Removing `a`.
mc.exe: <ERROR> Failed to remove `a`. remove a: The directory is not empty.
~> mc rm \\TMP\ss\
mc.exe: <ERROR> Failed to remove `\\TMP\ss\`. GetFileAttributesEx \\TMP\ss: The network name cannot be
~> mc rm C:\Users\vagrant\a\\\
Removing `C:\Users\vagrant\a\\\`.
mc.exe: <ERROR> Failed to remove `C:\Users\vagrant\a\\\`. remove C:\Users\vagrant\a\\\: The directory
~> mc rm C:\Users\vagrant\a\\\b\\\c\\\d
Removing `C:\Users\vagrant\a\\\b\\\c\\\d`.
~>
```

Comment (balamurugana) [reply cmd/rm-main.go]: We used `path.Clean()` to take care aliases like `s3` and `s3/`.  Hope return `path` from `url2Alias()` is clean.

Comment (poornas) [reply cmd/rm-main.go]: yes, added a comment for that as well.

File: cmd/rm-main.go [hunk 22]
```diff
@@ -121,17 +133,36 @@ func checkRmSyntax(ctx *cli.Context) {
 	isForce := ctx.Bool("force")
 	isRecursive := ctx.Bool("recursive")
 	isStdin := ctx.Bool("stdin")
-
+	isDangerous := ctx.Bool("dangerous")
+	isNamespaceRemoval := false
+	for _, url := range ctx.Args() {
+		// clean path for aliases like s3/
+		url = filepath.ToSlash(filepath.Clean(url))
```
Comment (balamurugana) [inline cmd/rm-main.go]: interestingly UNC path using  `/` is working in go1.9.2 by breaking the UNC path specification.

Comment (harshavardhana) [reply cmd/rm-main.go]: It is not breaking @balamurugana they automatically convert it internally properly. Before any Win32 calls are made `os` package converts them to necessary values. 

FWIW Win32 calls support `/` path separators as well.

Comment (balamurugana) [reply cmd/rm-main.go]: Check on windows how it behaves UNC path with `/`

Comment (poornas) [reply cmd/rm-main.go]:
```
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]> mc mb a/b/c/d/e
Bucket created successfully `a/b/c/d/e`.
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]> tree a
Folder PATH listing for volume Windows 10
Volume serial number is 00000200 4286:2744
C:\GO\SRC\GITHUB.COM\MINIO\MC\A
└───b
    └───c
        └───d
            └───e
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]> mc rm a/b/c/d/e
Removing `a/b/c/d/e`.
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]>
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]> mc rm //network1/blah/blah
mc.exe: <ERROR> Failed to remove `//network1/blah/blah`. Requested file `/blah/blah` not found
C:\GO\src\github.com\minio\mc [(0f4e134...) +0 ~1 -0 !]> mc rm --r --force //network1/blah/blah
mc.exe: <ERROR> Failed to remove `//network1/blah/blah` recursively. open /blah/blah: The system canno
h specified.
```

Comment (balamurugana) [reply cmd/rm-main.go]: No surprise go applications are working cleanly.  See my above comment.  Just add a comment what exactly i mentioned.

Comment (poornas) [reply cmd/rm-main.go]: done.

**Comment by harshavardhana** [comment]
Moving this to blocked as requested by @poornas  until @abperiasamy gives final review on the changes and UI.

**Comment by poornas** [comment]
after discussion with @abperiasamy , changed messaging for the  --force and --dangerous flags and error message if flags are not supplied for site wide rm command. This is unblocked now
