### PR TITLE
Fix credentials argument parsing

### LINKED ISSUE #2237: mc admin credentials fails with "cannot get a configured admin connection"
## Expected behaviour
Should set supplied credentials on Minio server

## Actual behaviour
`mc admin credentials TARGET ACCESS_KEY SECRET_KEY` fails with

`mc: <ERROR> Cannot get a configured admin connection. The specified alias: 123 not found`

## Steps to reproduce the behaviour
1. `mc admin credentials TARGET access_key secret_key`

## mc version
- (paste output of `mc version`)
commit id `ca96cfc`

### PR DESCRIPTION
**Pull request by krisis**
Fixes #2237

### CODE REVIEW

File: cmd/admin-credentials.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ func mainAdminCreds(ctx *cli.Context) error {
 	// TODO: if accessKey and secretKey are not supplied we should
 	// display the existing credentials. This needs GetCredentials
 	// support from Minio server.
-	accessKey, secretKey, aliasedURL := args.Get(0), args.Get(1), args.Get(2)
+	aliasedURL, accessKey, secretKey := args.Get(0), args.Get(1), args.Get(2)
```
Comment (harshavardhana) [inline cmd/admin-credentials.go]: :nauseated_face:
