### PR TITLE
Removed setting of http.Client Timeout for mc

### LINKED ISSUE #1719: mc cp fails with http.Client timeout for large objects
`mc cp` fails with http.Client Timeout error while copying large objects from minio server onto local disk

### PR DESCRIPTION
**Pull request by krisis**
Fixes #1719

### CODE REVIEW

File: client-s3.go [hunk 1]
```diff
@@ -36,6 +37,19 @@ import (
...
+		Dial: (&net.Dialer{
+			Timeout:   30 * time.Second,
+			KeepAlive: 30 * time.Second,
+		}).Dial,
+		TLSHandshakeTimeout: 10 * time.Second,
+		//Default ExpectContinueTimeout is 1sec
+		ExpectContinueTimeout: 3 * time.Second,
+	}
+)
+
```
Comment (krishnasrinivas) [inline client-s3.go]: you can make this a local variable

File: client-s3.go [hunk 2]
```diff
@@ -137,6 +124,16 @@ func newFactory() func(config *Config) (Client, *probe.Error) {
 		} else {
 			// We are using our own http.Transport value to have timeouts different from default
 			// where necessary.
+			mcDefaultTransport := http.Transport{
+				Proxy: http.ProxyFromEnvironment,
+				Dial: (&net.Dialer{
+					Timeout:   30 * time.Second,
+					KeepAlive: 30 * time.Second,
+				}).Dial,
+				TLSHandshakeTimeout: 10 * time.Second,
```
Comment (harshavardhana) [inline client-s3.go]: ResponseHeaderTimeout - is missing here.

Comment (krisis) [inline client-s3.go]: @harshavardhana what would be an appropriate `ResponseHeaderTimeout` for mc?
