### PR TITLE
Fix: mc rm to error when nonempty directory is deleted

### LINKED ISSUE #2242: mc rm not erroring out when deleting directory
## Expected behaviour

`mc rm` should exit with an error message when attempting to delete a non-empty directory inside object storage (when no flags are given). 

## Actual behaviour

See steps below:

```
$ mc mb play/testbucket1
Bucket created successfully `play/testbucket1`.
$ mc cp Dockerfile appveyor.yml play/testbucket1/folder1/folder2/
appveyor.yml:                  2.54 KB / 2.54 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 5.07 KB/s 0s
$ mc ls -r play/testbucket1/
[2017-08-24 16:29:49 IST]   779B folder1/folder2/Dockerfile
[2017-08-24 16:29:49 IST] 1.8KiB folder1/folder2/appveyor.yml
$ mc rm play/testbucket1/folder1
Removing `play/testbucket1/folder1`.
$ mc ls -r play/testbucket1/
[2017-08-24 16:29:49 IST]   779B folder1/folder2/Dockerfile
[2017-08-24 16:29:49 IST] 1.8KiB folder1/folder2/appveyor.yml
```

## Steps to reproduce the behaviour
See previous sectoin.

Originally raised by a user here - https://github.com/minio/minio/issues/4852

### PR DESCRIPTION
**Pull request by poornas**
Fixes #2242. 

When mc rm removes a single object, stat it on the server to see if it exists before proceeding with remove operation.

### CODE REVIEW

File: cmd/rm-main.go [hunk 1]
```diff
@@ -141,7 +141,7 @@ func removeSingle(url string, isIncomplete bool, isFake bool, older int) error {
 		errorIf(pErr.Trace(url), "Invalid argument `"+url+"`.")
 		return exitStatus(globalErrorExitStatus) // End of journey.
 	}
-	isFetchMeta := false
+	isFetchMeta := true
```
Comment (kannappanr) [inline cmd/rm-main.go]: Why do we need this isFetchMeta variable? It looks like it is being used only in the next line.

Comment (poornas) [reply cmd/rm-main.go]: the explicit flag definition is self documenting. Otherwise we would still need a comment to make the args passed to Stat function clear.
