### PR TITLE
diff: Change output UI

### LINKED ISSUE #2090: diff: ui change move from `only in first` to new format
## Expected behaviour

```
> /home/harsha/Photos/alice (11).jpg
> /home/harsha/Photos/alice (12).jpg
< https://play.minio.io:9000/testbucket/bin/7z
< https://play.minio.io:9000/testbucket/bin/7za
v https://play.minio.io:9000/testbucket/new-image.jpg
```

Here 

```
> - indicates file should be copied
< - indicates file should be deleted
v - indicates file differs in size. 
```

## Actual behaviour

Current output needs to be improved.

## Steps to reproduce the behaviour
Just build from master

## mc version
master

## System information
All operating systems.

### PR DESCRIPTION
**Pull request by vadmeste**
Use >, < and ! marks to represent differences between
source and destination.

Fixes #2090

### CODE REVIEW

File: cmd/diff-main.go [hunk 1]
```diff
@@ -52,12 +52,19 @@ FLAGS:
 DESCRIPTION:
   {{.Description}}
 
+OUTPUT:
+  Differences between source and destination are represented by some mark notations which have the following meaning:
```
Comment (harshavardhana) [inline cmd/diff-main.go]:
```
Differences between source and destination are represented by mark notations with following meaning:
```
