### PR TITLE
fixes cp not preserving ownership and other attrs

### LINKED ISSUE #3187: mc not preserving ownership
## Expected behavior
mc should preserve ownership

## Actual behavior
mc doesnt

## Steps to reproduce the behavior
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 sshd daemon 4096 Apr 22 15:10 scripts
~ mc mirror -a --remove --overwrite cont/box0/ dot9/cont/box0/
0 B / ?
~ rm -rf cont/box0
~ mc mirror -a dot9/cont/box0/ cont/box0/
...000/cont/box0/testFile: 149 B / 149 B 7.03 KiB/s 0s
~ ls -l cont/box0/ | grep scripts
drwxr-xr-x 2 root root 4096 Apr 22 15:13 scripts

@klauspost i am using -a flag which is same as --preserve as per ticket #3186 
Also tested with --preserve instead of -a, same result

## mc --version
mc version RELEASE.2020-04-19T19-17-53Z

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #3187 

When the preserve attributes flag, `-a`, and functionality was introduced, the assumption was that metadata index is going to be `"mc-attrs"`, however, it is `"X-Amz-Meta-Mc-Attrs"`.
The fix is to accept both indexes as valid values.

### CODE REVIEW

File: cmd/client-fs.go [hunk 1]
```diff
@@ -409,9 +409,13 @@ func (f *fsClient) put(reader io.Reader, size int64, metadata map[string][]strin
...
 func (f *fsClient) Put(ctx context.Context, reader io.Reader, size int64, metadata map[string]string, progress io.Reader, sse encrypt.ServerSide, md5, disableMultipart bool) (int64, *probe.Error) {
-	if metadata["mc-attrs"] != "" {
+	metaDataKey := "mc-attrs"
+	if metadata["X-Amz-Meta-Mc-Attrs"] != "" {
+		metaDataKey = "X-Amz-Meta-Mc-Attrs"
+	}
+	if metadata[metaDataKey] != "" {
 		meta := make(map[string][]string)
-		meta["mc-attrs"] = append(meta["mc-attrs"], metadata["mc-attrs"])
+		meta["mc-attrs"] = append(meta["mc-attrs"], metadata[metaDataKey])
```
Comment (harshavardhana) [inline cmd/client-fs.go:418]:
```suggestion
		meta[metaDataKey] = append(meta[metaDataKey], metadata[metaDataKey])
```

Comment (ebozduman) [reply cmd/client-fs.go:418]: @harshavardhana,
I did it this way, because I did not want to cause any regression, in case the same assumption is made in some other caller functions. If so, I also need to change those part of the codes in the same way.
Do you still want to see your suggestion to be implemented?

Comment (harshavardhana) [reply cmd/client-fs.go:418]: it looks a bit confusing @ebozduman we need to use a single metadata key.

Comment (ebozduman) [reply cmd/client-fs.go:418]: @harshavardhana, you suggested 2 ways:

1. I've just tested with your suggestion in your first comment.
As I expected, there is at least one or more callers which also expect the metadata key to be `"mc-attrs"`, hence the fix doesn't work. To make it work, there has to be more changes in this PR, if we choose to go this way.

2. Single key sounds better to me also
I can replace `"mc-attrs"` key with `"X-Amz-Meta-Mc-Attrs"` every where. (I'd still use a variable).
But, the only thing I am not %100 sure is that if there is any scenario where the key comes as `"mc-attrs"` and if we miss that code path, this PR is going to cause regression.

3. My original change (confusing, short and fastest solution)

Please let me know which option you want to go.

Comment (ebozduman) [reply cmd/client-fs.go]: After discussing with @kannappanr and @poornas, we've decided to go with single key, `"X-Amz-Meta-Mc-Attrs"` everywhere. This way, we also become S3 compliant.

**Comment by kannappanr** [comment]
PTAL build failure
