### PR TITLE
cli: fix -v output

### LINKED ISSUE #1915: cli: version produces wrong version
## Expected behaviour
```
$ mc --version
mc version 2016-12-05T22:51:51Z
```

## Actual behaviour
```
$ mc --version
mc version 0.0.0
```
## Steps to reproduce the behaviour
mc --version

## mc version
2016-12-05T22:51:51Z

## System information
All

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #1915

### CODE REVIEW

File: buildscripts/gen-ldflags.go [hunk 1]
```diff
@@ -28,10 +28,10 @@ import (
 
 func genLDFlags(version string) string {
 	var ldflagsStr string
-	ldflagsStr = "-X github.com/minio/mc/cmd.Version=" + version + " "
-	ldflagsStr = ldflagsStr + "-X github.com/minio/mc/cmd.ReleaseTag=" + releaseTag(version) + " "
-	ldflagsStr = ldflagsStr + "-X github.com/minio/mc/cmd.CommitID=" + commitID() + " "
-	ldflagsStr = ldflagsStr + "-X github.com/minio/mc/cmd.ShortCommitID=" + commitID()[:12]
+	ldflagsStr = "-X github.com/minio/mc/cmd.mcVersion=" + version + " "
```
Comment (harshavardhana) [inline buildscripts/gen-ldflags.go]: These were purposefully kept to not have 'mc' and acquire the namespace.  Do not change this to 'mcVersion'
