### PR TITLE
Error out in list policy if policy doesn't exist

### LINKED ISSUE #2758: Return code from "mc admin policy list fdsfdsfds" is 0 even when policy doesn't exist
## Expected behavior
provide a return code to confirm a policy doesn't exist.

## Actual behavior
I'm trying to find out if a policy exists or not with the `mc` client tool. 

C:\Users\user>mc admin policy list minio
readonly
readwrite
writeonly

C:\Users\user>echo %errorlevel%
0

C:\Users\user>mc admin policy list minio fdasfdas
fdasfdas

C:\Users\user>echo %errorlevel%
0

The policy fdasfdas does not exist, as you can see by the output of the first `mc admin policy list minio` command. But the exit code of `mc admin policy list minio fdasfdas` is 0 - success.

## Steps to reproduce the behavior
Examine the return code for a non-existent policy:
mc admin policy list minio fdasfdas

## mc version
Version: 2019-04-10T22:11:28Z
Release-tag: RELEASE.2019-04-10T22-11-28Z
Commit-id: ea469140d50b0240501963666e1de19c6d37f812

### PR DESCRIPTION
**Pull request by sinhaashish**
Error out in case of list policy `mc admin policy list minio fdasfdas` if the policy ` fdasfdas` is not present.

Closes #2758

### CODE REVIEW

File: cmd/admin-policy-list.go [hunk 1]
```diff
@@ -76,11 +77,15 @@ func mainAdminPolicyList(ctx *cli.Context) error {
 	fatalIf(probe.NewError(e).Trace(args...), "Cannot list policy")
 
 	if policyName := args.Get(1); policyName != "" {
-		printMsg(userPolicyMessage{
-			op:         "list",
-			Policy:     policyName,
-			PolicyJSON: policies[policyName],
-		})
+		if fmt.Sprintf("%s", policies[policyName]) != "" {
```
Comment (ebozduman) [inline cmd/admin-policy-list.go]: `policies` is of type `map[string][]byte`.
So, we can simply check the length of the byte array if zero or not, IMHO:
```
    if len(policies[policyName]) != 0 {
```

Comment (sinhaashish) [reply cmd/admin-policy-list.go]: :thumbsup: Modified.

File: cmd/admin-policy-list.go [hunk 2]
```diff
@@ -76,11 +77,15 @@ func mainAdminPolicyList(ctx *cli.Context) error {
...
-			PolicyJSON: policies[policyName],
-		})
+		if len(policies[policyName]) != 0 {
+			printMsg(userPolicyMessage{
+				op:         "list",
+				Policy:     policyName,
+				PolicyJSON: policies[policyName],
+			})
+		} else {
+			fatalIf(probe.NewError(fmt.Errorf("The specified policy: %s not found", policyName)), "Cannot find policy")
```
Comment (vadmeste) [inline cmd/admin-policy-list.go]: Neat change: The error message can be better this way:

`fatalIf(probe.NewError(fmt.Errorf("`%s` is not found", policyName)), "Cannot list the policy")`

Comment (sinhaashish) [reply cmd/admin-policy-list.go]: Done.
