### PR TITLE
Display config in correct format when json flag is used

### LINKED ISSUE #2530: Adding --json to `mc admin config get` outputs invalid config information
When running the command `mc admin config get play | jq `, you get output regarding the configuration of the cluster.  If you add --json, (e.g., `mc admin config get play --json| jq`), it prints string of random alphanumeric characters.

## Expected Behavior
--json should show usable information in the config field
## Current Behavior
```mc admin config get play --json| jq
{
  "status": "success",
  "config": "eyJ2ZXJzaW9uIjoiMjgiLCJjcmVkZW50aWFsIjp7ImFjY2Vzc0tleSI6IlEzQU0zVVE4NjdTUFFRQTQzUDJGIiwic2VjcmV0S2V5IjoienVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURyJ9LCJyZWdpb24iOiIiLCJicm93c2VyIjoib24iLCJ3b3JtIjoib2ZmIiwiZG9tYWluIjoiIiwic3RvcmFnZWNsYXNzIjp7InN0YW5kYXJkIjoiIiwicnJzIjoiIn0sImNhY2hlIjp7ImRyaXZlcyI6W10sImV4cGlyeSI6OTAsIm1heHVzZSI6ODAsImV4Y2x1ZGUiOltdfSwia21zIjp7InZhdWx0Ijp7ImVuZHBvaW50IjoiIiwiYXV0aCI6eyJ0eXBlIjoiIiwiYXBwcm9sZSI6eyJpZCI6IiIsInNlY3JldCI6IiJ9fSwia2V5LWlkIjp7Im5hbWUiOiIiLCJ2ZXJzaW9uIjowfX19LCJub3RpZnkiOnsiYW1xcCI6eyIxIjp7ImVuYWJsZSI6ZmFsc2UsInVybCI6IiIsImV4Y2hhbmdlIjoiIiwicm91dGluZ0tleSI6IiIsImV4Y2hhbmdlVHlwZSI6IiIsImRlbGl2ZXJ5TW9kZSI6MCwibWFuZGF0b3J5IjpmYWxzZSwiaW1tZWRpYXRlIjpmYWxzZSwiZHVyYWJsZSI6ZmFsc2UsImludGVybmFsIjpmYWxzZSwibm9XYWl0IjpmYWxzZSwiYXV0b0RlbGV0ZWQiOmZhbHNlfX0sImVsYXN0aWNzZWFyY2giOnsiMSI6eyJlbmFibGUiOnRydWUsImZvcm1hdCI6Im5hbWVzcGFjZSIsInVybCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTIwMCIsImluZGV4IjoibWluaW9fZXZlbnRzIn19LCJrYWZrYSI6eyIxIjp7ImVuYWJsZSI6ZmFsc2UsImJyb2tlcnMiOm51bGwsInRvcGljIjoiIn19LCJtcXR0Ijp7IjEiOnsiZW5hYmxlIjpmYWxzZSwiYnJva2VyIjoiIiwidG9waWMiOiIiLCJxb3MiOjAsImNsaWVudElkIjoiIiwidXNlcm5hbWUiOiIiLCJwYXNzd29yZCI6IiIsInJlY29ubmVjdEludGVydmFsIjowLCJrZWVwQWxpdmVJbnRlcnZhbCI6MH19LCJteXNxbCI6eyIxIjp7ImVuYWJsZSI6ZmFsc2UsImZvcm1hdCI6IiIsImRzblN0cmluZyI6IiIsInRhYmxlIjoiIiwiaG9zdCI6IiIsInBvcnQiOiIiLCJ1c2VyIjoiIiwicGFzc3dvcmQiOiIiLCJkYXRhYmFzZSI6IiJ9fSwibmF0cyI6eyIxIjp7ImVuYWJsZSI6ZmFsc2UsImFkZHJlc3MiOiIiLCJzdWJqZWN0IjoiIiwidXNlcm5hbWUiOiIiLCJwYXNzd29yZCI6IiIsInRva2VuIjoiIiwic2VjdXJlIjpmYWxzZSwicGluZ0ludGVydmFsIjowLCJzdHJlYW1pbmciOnsiZW5hYmxlIjpmYWxzZSwiY2x1c3RlcklEIjoiIiwiY2xpZW50SUQiOiIiLCJhc3luYyI6ZmFsc2UsIm1heFB1YkFja3NJbmZsaWdodCI6MH19fSwicG9zdGdyZXNxbCI6eyIxIjp7ImVuYWJsZSI6ZmFsc2UsImZvcm1hdCI6IiIsImNvbm5lY3Rpb25TdHJpbmciOiIiLCJ0YWJsZSI6IiIsImhvc3QiOiIiLCJwb3J0IjoiIiwidXNlciI6IiIsInBhc3N3b3JkIjoiIiwiZGF0YWJhc2UiOiIifX0sInJlZGlzIjp7IjEiOnsiZW5hYmxlIjpmYWxzZSwiZm9ybWF0IjoiIiwiYWRkcmVzcyI6IiIsInBhc3N3b3JkIjoiIiwia2V5IjoiIn19LCJ3ZWJob29rIjp7IjEiOnsiZW5hYmxlIjpmYWxzZSwiZW5kcG9pbnQiOiIifX19LCJsb2dnZXIiOnsiY29uc29sZSI6eyJlbmFibGVkIjp0cnVlfSwiaHR0cCI6eyIxIjp7ImVuYWJsZWQiOmZhbHNlLCJlbmRwb2ludCI6IiJ9fX19"
}
```

## Steps to Reproduce (for bugs)
Add --json to `mc admin config get play`

 $ mc version
Version: 2018-09-06T23:26:56Z
Release-tag: RELEASE.2018-09-06T23-26-56Z
Commit-id: 0d0638b398e69887b5d7c0abcfb32882fd37b1fd

### PR DESCRIPTION
**Pull request by kannappanr**
Previously config was encoded in Base64 format. Fixed the code to not do that anymore.
Fixes #2530

### CODE REVIEW

File: cmd/admin-config-get.go [hunk 1]
```diff
@@ -59,10 +60,12 @@ func (u configGetMessage) String() string {
 // JSON jsonified service status Message message.
 func (u configGetMessage) JSON() string {
 	u.Status = "success"
-	statusJSONBytes, e := json.Marshal(u)
+	statusJSONBytes, e := json.MarshalIndent(u, "", "    ")
```
Comment (ebozduman) [inline cmd/admin-config-get.go]: `"\t"` can be used instead of bunch of space characters, like
`json.MarshalIndent(u, "", "\t")`

File: cmd/admin-config-get.go [hunk 2]
```diff
@@ -59,10 +60,12 @@ func (u configGetMessage) String() string {
...
 	fatalIf(probe.NewError(e), "Unable to marshal into JSON.")
 
-	return string(statusJSONBytes)
+	//Remove \n and \t from config.json string
```
Comment (ebozduman) [inline cmd/admin-config-get.go]: It is not a big deal, but it could be confusing to call `MarshalIndent` above to introduce indentations and new lines and then remove the same control characters here. 
I guess, it would be clearer if we make the distinction between these 2 cases by adding comments, that we are removing the tabs and new line control characters from the internal config fields from `u.Config` at sub-level, not `config.json` file which doesn't exist anymore.

Comment (kannappanr) [reply cmd/admin-config-get.go]: done

File: cmd/admin-config-get.go (hunk 1 above)
Comment (kannappanr) [reply cmd/admin-config-get.go]: done

File: cmd/admin-config-get.go [hunk 3]
```diff
@@ -59,10 +60,12 @@ func (u configGetMessage) String() string {
 // JSON jsonified service status Message message.
 func (u configGetMessage) JSON() string {
 	u.Status = "success"
-	statusJSONBytes, e := json.Marshal(u)
+	statusJSONBytes, e := json.MarshalIndent(u, "", "\t")
 	fatalIf(probe.NewError(e), "Unable to marshal into JSON.")
 
-	return string(statusJSONBytes)
+	//Remove \n and \t from u.Config which holds the config data
```
Comment (harshavardhana) [inline cmd/admin-config-get.go]: comment `//<space><your_words>`

File: cmd/admin-config-get.go [hunk 4]
```diff
@@ -59,10 +60,12 @@ func (u configGetMessage) String() string {
...
+	r := strings.NewReplacer(`\n`, "", `\t`, "")
```
Comment (harshavardhana) [inline cmd/admin-config-get.go]: write this in one line? 

```
strings.NewReplacer().Replace(string) 
```

Comment (kannappanr) [reply cmd/admin-config-get.go]: done

File: cmd/admin-config-get.go (hunk 3 above)
Comment (kannappanr) [reply cmd/admin-config-get.go]: done
