### PR TITLE
Fix all cli commands to have consistent UI

### LINKED ISSUE #2038: `mc share -help` and `mc share` with no cli arguments give different help messages
## Actual behaviour
```shell
➜  mc git:(master) ✗ mc share
NAME:
   mc share - Generate URL for sharing.

USAGE:
   mc share [FLAGS] COMMAND

FLAGS:
  --config-folder value, -C value  Path to configuration folder. (default: "/home/kp/.mc")
  --quiet, -q                      Suppress chatty console output.
  --no-color                       Disable color theme.
  --json                           Enable JSON formatted output.
  --debug                          Enable debug output.
  --insecure                       Disable SSL certificate verification.
  --help, -h                       Show help.
  
COMMANDS:
   download  Generate URLs for download access.
   upload    Generate `curl` command to upload objects without requiring access/secret keys.
   list      List previously shared objects and folders.
   help, h   Shows a list of commands or help for one command
```

```shell
➜  mc git:(master) ✗ mc share -help
NAME:
   mc share - Generate URL for sharing.

USAGE:
   mc share command [command options] [arguments...]

COMMANDS:
     download  Generate URLs for download access.
     upload    Generate `curl` command to upload objects without requiring access/secret keys.
     list      List previously shared objects and folders.

OPTIONS:
   --config-folder value, -C value  Path to configuration folder. (default: "/home/kp/.mc")
   --quiet, -q                      Suppress chatty console output.
   --no-color                       Disable color theme.
   --json                           Enable JSON formatted output.
   --debug                          Enable debug output.
   --insecure                       Disable SSL certificate verification.
   --help, -h                       Show help.
```
## Steps to reproduce the behaviour
1. mc share
2. mc share -help

## mc version
```
Version: 2017-02-27T06:47:51Z
Release-tag: DEVELOPMENT.2017-02-27T06-47-51Z
Commit-id: 798775775b94e833cbf5128f455113f2f2d962af
```

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #2038

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can you pull this PR in and try all the commands @krisis - i verified from my end. Check even for wrongly spaced characters too.

File: cmd/admin-service.go [hunk 1]
```diff
@@ -38,21 +38,14 @@ FLAGS:
   {{range .VisibleFlags}}{{.}}
   {{end}}
 COMMANDS:
-   {{range .VisibleCommands}}{{join .Names ", "}}{{ "\t" }}{{.Usage}}
-   {{end}}
+  {{range .VisibleCommands}}{{join .Names ", "}}{{ "\t" }}{{.Usage}}
```
Comment (krisis) [inline cmd/admin-service.go]: Can't the custom template be stored as a package-level constant?

Comment (harshavardhana) [inline cmd/admin-service.go]: Not for everything is common. Each command has their own examples which need to be captured. Custom template is provided to avoid the default template in the first place.

Comment (harshavardhana) [inline cmd/admin-service.go]: Actually help template is not needed for these ones. Removing them.

Comment (krisis) [inline cmd/admin-service.go]: Not everything is common but some of them are similar.
E.g, 
- cp-main and cat-main have the same template.
- ls-main and mb-main have the same template.
We can reduce duplicating the string and be consistent.

**Comment by harshavardhana** [comment]
Fixed more template UI elements.
