### PR TITLE
Ignore broken symlink durring mirror

### LINKED ISSUE #2604: mc mirror aborts on a broken symlink
Hello,

mc mirror aborts on a broken symlink:

```
$ mc mirror \
  --overwrite \
  --remove \
  --encrypt-key "mycloud/host1=<REDACTED>" \
  --exclude ".cache/*" \
  /home mycloud/host1/

.../Default/Web Data-journal:  2.07 MB / 2.33 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░┃ 75.30 KB/s
mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user1/.config/google-chrome/SingletonCookie` has broken symlink
```

Is this expected?

## Expected behavior

I am expecting minio to mirror everything except the broken symlinks instead of just aborting the entire mirror process at the first broken symlink it encounters.

## minio client version

```
$ mc version
Version: 2018-10-18T00:40:05Z
Release-tag: RELEASE.2018-10-18T00-40-05Z
Commit-id: 0dd32c1b26f05e7f94f76f2ceb62b5229836b009
```

## minio server version

```
  Version : 2018-10-11T20:22:03Z
```

### PR DESCRIPTION
**Pull request by Praveenrajmani**
The mirror action should fallback on errors and continue mirroring other non-infected objects rather failing on the first catch.

Fixes #2604

### CODE REVIEW

**Comment by arno01** [comment]
@Praveenrajmani just FYI: I've tested the https://github.com/minio/mc/pull/2607/commits/b1dea2c03e74b2dfe0f98ea88574ff1f6b813af7 locally, it worked for me :-)

**Comment by arno01** [comment]
@Praveenrajmani not sure if this is related to this PR but, when I do mirror my ``/home/user``,  I am seeing the error messages repeat hundreds of times (or even more) for the same symlinks.. any clue why?

```
mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
...
```


And then, if I am using ``--remove`` flag with ``mc mirror``, it always removing the data before mirroring it...:

```
Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_wraptext.png`.
Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_wraptext.png`.
Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_zoom.png`.
Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_zoom.png`.
...
```

Whilst the mc's help says that ``--remove`` should only remove the extraneous files on the target...

**Comment by Praveenrajmani** [comment]
> Unable to perform a mirror action



> @Praveenrajmani not sure if this is related to this PR but, when I do mirror my `/home/user`, I am seeing the error messages repeat hundreds of times (or even more) for the same symlinks.. any clue why?
> 
> ```
> mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
> mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
> mc: <ERROR> Unable to perform a mirror action. Requested file `/home/user/.config/google-chrome/SingletonCookie` has broken symlink
> ...
> ```
> 
> And then, if I am using `--remove` flag with `mc mirror`, it always removing the data before mirroring it...:
> 
> ```
> Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_wraptext.png`.
> Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_wraptext.png`.
> Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_zoom.png`.
> Removing `mycloud/mbp/.config/libreoffice/4/cache/tango/150/cmd/lc_zoom.png`.
> ...
> ```
> 
> Whilst the mc's help says that `--remove` should only remove the extraneous files on the target...
> I was using the mc with this PR in place.

I guess the first one is related to this PR, I am trying to reproduce this ..

**Comment by Praveenrajmani** [comment]
Can you try with the updated change now and see if it still exists @arno01

**Comment by arno01** [comment]
@Praveenrajmani  https://github.com/minio/mc/pull/2607/commits/34757d20ca22cf13e4d2c68885e73e32d5fece1b fixed the "duplicated errors" and the data removal problems described above.
So, probably, both were related.

What I've noticed strange is that mc mirror shows that it is backing up more data on the 3rd run.. It feels like it had missed some before. Not sure.

**Comment by harshavardhana** [comment]
> @Praveenrajmani [34757d2](https://github.com/minio/mc/commit/34757d20ca22cf13e4d2c68885e73e32d5fece1b) fixed the "duplicated errors" and the data removal problems described above.
> So, probably, both were related.
> 
> What I've noticed strange is that mc mirror shows that it is backing up more data on the 3rd run.. It feels like it had missed some before. Not sure.

Is there anything pending on this PR @Praveenrajmani before review?

**Comment by Praveenrajmani** [comment]
> > @Praveenrajmani [34757d2](https://github.com/minio/mc/commit/34757d20ca22cf13e4d2c68885e73e32d5fece1b) fixed the "duplicated errors" and the data removal problems described above.
> > So, probably, both were related.
> > What I've noticed strange is that mc mirror shows that it is backing up more data on the 3rd run.. It feels like it had missed some before. Not sure.
> 
> Is there anything pending on this PR @Praveenrajmani before review?

No @harshavardhana . The PR is ready for review

**Comment by vadmeste** [comment]
@Praveenrajmani this PR is basically the revert of this PR https://github.com/minio/mc/pull/2440 and we had an unfinished discussion with AB about what to do with broken symlinks.

I think the best way to fix this is to:
1. Make difference() quits for any error.
2. Make difference() returns errors as minimum as possible.

I think that FS listing should not return broken symlink error here, it can still return a file with size = -1 in this case (even `mc ls` will be able to show that file in red color). Then, the error can be manifested later when copying and then mc will be able to decide if it can ignore this error or not (better context there).

**Comment by Praveenrajmani** [comment]
> @Praveenrajmani this PR is basically the revert of this PR #2440 and we had an unfinished discussion with AB about what to do with broken symlinks.
> 
> I think the best way to fix this is to:
> 
>     1. Make difference() quits for any error.
> 
>     2. Make difference() returns errors as minimum as possible.
> 
> 
> I think that FS listing should not return broken symlink error here, it can still return a file with size = -1 in this case (even `mc ls` will be able to show that file in red color). Then, the error can be manifested later when copying and then mc will be able to decide if it can ignore this error or not (better context there).

Agreed.. I think the better fix is to return such files with size=-1

**Comment by Praveenrajmani** [comment]
PTAL @vadmeste  @harshavardhana

File: cmd/client-fs.go [hunk 1]
```diff
@@ -670,9 +670,12 @@ func (f *fsClient) listInRoutine(contentCh chan<- *clientContent) {
 					}
 					continue
 				}
+				// Fallback on broken symlinks.
```
Comment (vadmeste) [inline cmd/client-fs.go]: @Praveenrajmani I think there is a better solution for this, you can os os.Lstat() instead of os.Stat()

Comment (Praveenrajmani) [reply cmd/client-fs.go]: Done

File: cmd/client-fs.go [hunk 2]
```diff
@@ -849,10 +853,13 @@ func (f *fsClient) listRecursiveInRoutine(contentCh chan *clientContent) {
 					}
 					return nil
 				}
-				// Ignore in-accessible broken symlinks.
 				if os.IsNotExist(e) {
+					// Lstat makes no attempt to follow the broken link.
+					_, err := os.Lstat(fp)
```
Comment (harshavardhana) [inline cmd/client-fs.go]: err is being shadowed here use `e` instead of `err`

File: cmd/client-fs.go [hunk 3]
```diff
@@ -671,8 +671,12 @@ func (f *fsClient) listInRoutine(contentCh chan<- *clientContent) {
 					continue
 				}
 				if os.IsNotExist(e) {
+					// Lstat makes no attempt to follow the broken link.
+					_, e = os.Lstat(filepath.Join(fpath, fi.Name()))
```
Comment (vadmeste) [inline cmd/client-fs.go]: fi is null here when there is an error due to L666.

Comment (Praveenrajmani) [reply cmd/client-fs.go]: Done :+1:
